"""
AKAAL Platform 6 — Enterprise Governance Domain Enums.
"""

from enum import Enum


class LifecycleState(str, Enum):
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    RETIRED = "RETIRED"
    ARCHIVED = "ARCHIVED"


class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"
    EXPIRED = "EXPIRED"
    OVERRIDDEN = "OVERRIDDEN"


class PolicyCategory(str, Enum):
    VALIDATION = "VALIDATION"
    HEALING = "HEALING"
    REPLICATION = "REPLICATION"
    RELIABILITY = "RELIABILITY"
    RESILIENCE = "RESILIENCE"
    SECURITY = "SECURITY"
    OPERATIONAL = "OPERATIONAL"


class SoDConflictType(str, Enum):
    SELF_APPROVAL = "SELF_APPROVAL"
    ROLE_CONFLICT = "ROLE_CONFLICT"
    COLLUSION_RISK = "COLLUSION_RISK"
    POLICY_CONTRADICTION = "POLICY_CONTRADICTION"


class EmergencyReason(str, Enum):
    OUTAGE_MITIGATION = "OUTAGE_MITIGATION"
    DATA_CORRUPTION_PREVENTION = "DATA_CORRUPTION_PREVENTION"
    SECURITY_BREACH_CONTAINMENT = "SECURITY_BREACH_CONTAINMENT"
    REGULATORY_COMPLIANCE_ORDER = "REGULATORY_COMPLIANCE_ORDER"
