"""akaalPipeline.contracts package."""

from akaalPipeline.contracts.correlation import PipelineCorrelationContext
from akaalPipeline.contracts.enums import (
    AttemptLifecycleState,
    CapabilityDimension,
    MigrationLifecycleState,
    MigrationMode,
    OperationStatus,
    PipelineErrorCode,
    ScheduleLifecycleState,
    SideEffectClassification,
)
from akaalPipeline.contracts.errors import (
    CheckpointRejectedError,
    ContractIncompatibleError,
    IdempotencyConflictError,
    IneligibleError,
    LeaseConflictError,
    NotReadyError,
    PersistenceError,
    PipelineError,
    PolicyDeniedError,
    RevisionConflictError,
    StaleResultError,
    UnableToAcquireLeaseError,
    UnboundEngineError,
    UnavailableError,
    UnsupportedModeError,
    make_pipeline_error,
)
from akaalPipeline.contracts.ids import (
    AttemptId,
    CheckpointId,
    DefinitionRevisionId,
    ExecutionPlanId,
    InitializationId,
    InvocationId,
    MigrationId,
    OperationId,
    PlanVersionId,
    ProjectId,
    ScheduleId,
    TenantId,
    WorkspaceId,
)
from akaalPipeline.contracts.serialization import assert_json_safe, canonical_fingerprint, canonical_serialize

__all__ = [
    "MigrationId",
    "DefinitionRevisionId",
    "PlanVersionId",
    "ExecutionPlanId",
    "InitializationId",
    "AttemptId",
    "OperationId",
    "InvocationId",
    "CheckpointId",
    "ScheduleId",
    "TenantId",
    "ProjectId",
    "WorkspaceId",
    "MigrationLifecycleState",
    "AttemptLifecycleState",
    "ScheduleLifecycleState",
    "OperationStatus",
    "MigrationMode",
    "SideEffectClassification",
    "CapabilityDimension",
    "PipelineErrorCode",
    "PipelineError",
    "RevisionConflictError",
    "IdempotencyConflictError",
    "UnboundEngineError",
    "UnavailableError",
    "UnsupportedModeError",
    "IneligibleError",
    "NotReadyError",
    "PolicyDeniedError",
    "LeaseConflictError",
    "UnableToAcquireLeaseError",
    "StaleResultError",
    "CheckpointRejectedError",
    "ContractIncompatibleError",
    "PersistenceError",
    "make_pipeline_error",
    "canonical_serialize",
    "canonical_fingerprint",
    "assert_json_safe",
    "PipelineCorrelationContext",
]
