"""akaalPipeline.contracts.enums
=============================
Canonical enums for state, modes, error codes, and classifications.
"""

from __future__ import annotations

from enum import Enum


class MigrationLifecycleState(str, Enum):
    DRAFT = "DRAFT"
    CONFIGURING = "CONFIGURING"
    DISCOVERED = "DISCOVERED"
    PLANNED = "PLANNED"
    GOVERNANCE_PENDING = "GOVERNANCE_PENDING"
    AUTHORIZED = "AUTHORIZED"
    INITIALIZED = "INITIALIZED"
    ACTIVE = "ACTIVE"
    CANCELLATION_PENDING = "CANCELLATION_PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    ARCHIVED = "ARCHIVED"



class AttemptLifecycleState(str, Enum):
    REQUESTED = "REQUESTED"
    ADMITTED = "ADMITTED"
    LEASED = "LEASED"
    DISPATCHED = "DISPATCHED"
    RUNNING = "RUNNING"
    PAUSING = "PAUSING"
    PAUSED = "PAUSED"
    RECOVERING = "RECOVERING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    COMPENSATING = "COMPENSATING"
    COMPENSATED = "COMPENSATED"


class ScheduleLifecycleState(str, Enum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    ARMED = "ARMED"
    ACTIVATING = "ACTIVATING"
    CONSUMED = "CONSUMED"
    CANCELLED = "CANCELLED"
    INVALIDATED = "INVALIDATED"


class OperationStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class PlanExecutionStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class NodeExecutionState(str, Enum):
    BLOCKED = "BLOCKED"
    READY = "READY"
    ACCEPTED = "ACCEPTED"
    DISPATCHED = "DISPATCHED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"



class MigrationMode(str, Enum):
    M1_BULK = "M1"
    M2_BULK_CDC = "M2"
    M3_CDC = "M3"
    M4_INCREMENTAL = "M4"
    M5_STATE_SYNC = "M5"
    M6_SCHEMA_ONLY = "M6"
    M7_DATA_ONLY = "M7"
    M8_VALIDATION_ONLY = "M8"


class SideEffectClassification(str, Enum):
    READ_ONLY = "READ_ONLY"
    REVERSIBLE = "REVERSIBLE"
    IRREVERSIBLE = "IRREVERSIBLE"
    DESTRUCTIVE = "DESTRUCTIVE"


class CapabilityDimension(str, Enum):
    CATALOG = "CATALOG"
    BINDING = "BINDING"
    CONTRACT = "CONTRACT"
    HEALTH = "HEALTH"
    DEPENDENCY = "DEPENDENCY"
    ELIGIBILITY = "ELIGIBILITY"
    POLICY = "POLICY"
    READINESS = "READINESS"


class PipelineErrorCode(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    INVALID_TRANSITION = "INVALID_TRANSITION"
    UNBOUND = "UNBOUND"
    UNAVAILABLE = "UNAVAILABLE"
    UNSUPPORTED = "UNSUPPORTED"
    INELIGIBLE = "INELIGIBLE"
    NOT_READY = "NOT_READY"
    POLICY_DENIED = "POLICY_DENIED"
    LEASE_CONFLICT = "LEASE_CONFLICT"
    UNABLE_TO_ACQUIRE_LEASE = "UNABLE_TO_ACQUIRE_LEASE"
    STALE_RESULT = "STALE_RESULT"
    CHECKPOINT_REJECTED = "CHECKPOINT_REJECTED"
    CONTRACT_INCOMPATIBLE = "CONTRACT_INCOMPATIBLE"
    PERSISTENCE_FAILURE = "PERSISTENCE_FAILURE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
