"""akaalPipeline.contracts.enums
=============================
Canonical enums for state, modes, error codes, and classifications.
"""

from __future__ import annotations

from enum import Enum


class MigrationLifecycleState(str, Enum):
    DRAFT = "DRAFT"
    CONFIGURING = "CONFIGURING"
    DISCOVERED = "DISCOVERED"
    PLANNED = "PLANNED"
    GOVERNANCE_PENDING = "GOVERNANCE_PENDING"
    AUTHORIZED = "AUTHORIZED"
    INITIALIZED = "INITIALIZED"
    ACTIVE = "ACTIVE"
    CANCELLATION_PENDING = "CANCELLATION_PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    ARCHIVED = "ARCHIVED"


class AttemptLifecycleState(str, Enum):
    REQUESTED = "REQUESTED"
    ADMITTED = "ADMITTED"
    LEASED = "LEASED"
    DISPATCHED = "DISPATCHED"
    RUNNING = "RUNNING"
    PAUSING = "PAUSING"
    PAUSED = "PAUSED"
    RECOVERING = "RECOVERING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    COMPENSATING = "COMPENSATING"
    COMPENSATED = "COMPENSATED"


class ScheduleLifecycleState(str, Enum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    ARMED = "ARMED"
    ACTIVATING = "ACTIVATING"
    CONSUMED = "CONSUMED"
    CANCELLED = "CANCELLED"
    INVALIDATED = "INVALIDATED"


class OperationStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class PlanExecutionStatus(str, Enum):
    ACCEPTED = "ACCEPTED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class NodeExecutionState(str, Enum):
    BLOCKED = "BLOCKED"
    READY = "READY"
    ACCEPTED = "ACCEPTED"
    DISPATCHED = "DISPATCHED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class MigrationMode(str, Enum):
    M1_BULK = "M1"
    M2_BULK_CDC = "M2"
    M3_CDC = "M3"
    M4_INCREMENTAL = "M4"
    M5_STATE_SYNC = "M5"
    M6_SCHEMA_ONLY = "M6"
    M7_DATA_ONLY = "M7"
    M8_VALIDATION_ONLY = "M8"


class SideEffectClassification(str, Enum):
    READ_ONLY = "READ_ONLY"
    REVERSIBLE = "REVERSIBLE"
    IRREVERSIBLE = "IRREVERSIBLE"
    DESTRUCTIVE = "DESTRUCTIVE"


class CapabilityDimension(str, Enum):
    CATALOG = "CATALOG"
    BINDING = "BINDING"
    CONTRACT = "CONTRACT"
    HEALTH = "HEALTH"
    DEPENDENCY = "DEPENDENCY"
    ELIGIBILITY = "ELIGIBILITY"
    POLICY = "POLICY"
    READINESS = "READINESS"


class PipelineErrorCode(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    REVISION_CONFLICT = "REVISION_CONFLICT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    INVALID_TRANSITION = "INVALID_TRANSITION"
    UNBOUND = "UNBOUND"
    UNAVAILABLE = "UNAVAILABLE"
    UNSUPPORTED = "UNSUPPORTED"
    INELIGIBLE = "INELIGIBLE"
    NOT_READY = "NOT_READY"
    POLICY_DENIED = "POLICY_DENIED"
    LEASE_CONFLICT = "LEASE_CONFLICT"
    UNABLE_TO_ACQUIRE_LEASE = "UNABLE_TO_ACQUIRE_LEASE"
    STALE_RESULT = "STALE_RESULT"
    CHECKPOINT_REJECTED = "CHECKPOINT_REJECTED"
    CONTRACT_INCOMPATIBLE = "CONTRACT_INCOMPATIBLE"
    PERSISTENCE_FAILURE = "PERSISTENCE_FAILURE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    SOD_VIOLATION = "SOD_VIOLATION"
    QUORUM_NOT_MET = "QUORUM_NOT_MET"
    STALE_GENERATION = "STALE_GENERATION"
    SEAL_MISMATCH = "SEAL_MISMATCH"
    KEY_REVOKED = "KEY_REVOKED"
    CLOCK_SKEW_DETECTED = "CLOCK_SKEW_DETECTED"
    CSPRNG_UNAVAILABLE = "CSPRNG_UNAVAILABLE"
    CRYPTOGRAPHIC_DEPENDENCY_ERROR = "CRYPTOGRAPHIC_DEPENDENCY_ERROR"


# ---------------------------------------------------------------------------
# P5.9 Enterprise Security & Governance Enums
# ---------------------------------------------------------------------------

class PrincipalType(str, Enum):
    HUMAN = "HUMAN"
    SERVICE = "SERVICE"
    MACHINE = "MACHINE"
    WORKLOAD = "WORKLOAD"
    SYSTEM = "SYSTEM"


class KDFAlgorithm(str, Enum):
    ARGON2ID = "ARGON2ID"
    PBKDF2_SHA256 = "PBKDF2_SHA256"


class GrantSubjectType(str, Enum):
    PRINCIPAL = "PRINCIPAL"
    GROUP = "GROUP"


class GrantResourceType(str, Enum):
    ORGANIZATION = "ORGANIZATION"
    WORKSPACE = "WORKSPACE"
    PROJECT = "PROJECT"
    MIGRATION = "MIGRATION"
    SYSTEM = "SYSTEM"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class KeyPurpose(str, Enum):
    EXECUTION_SIGNING = "EXECUTION_SIGNING"
    AUDIT_SEAL = "AUDIT_SEAL"
    TOKEN_ENCRYPT = "TOKEN_ENCRYPT"
    RECEIPT_SIGNING = "RECEIPT_SIGNING"


class KeyAlgorithm(str, Enum):
    ED25519 = "ED25519"
    HMAC_SHA256 = "HMAC_SHA256"
    AES_256_GCM = "AES_256_GCM"


class KeyStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RETIRED = "RETIRED"
    REVOKED = "REVOKED"


class SecurityAlertSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TenantStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    DECOMMISSIONED = "DECOMMISSIONED"


class WorkspaceStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"


class PolicyEffect(str, Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"


class AuditDecision(str, Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    MUTATE = "MUTATE"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"


class FencingAssuranceClass(str, Enum):
    ATOMIC_FENCEABLE = "ATOMIC_FENCEABLE"
    CONDITIONAL_VERSIONED = "CONDITIONAL_VERSIONED"
    PRE_OPERATION_ONLY = "PRE_OPERATION_ONLY"
    COMPENSATABLE_NON_ATOMIC = "COMPENSATABLE_NON_ATOMIC"
    UNSUPPORTED_FAIL_CLOSED = "UNSUPPORTED_FAIL_CLOSED"
