"""
Akaal — Trigger Fallback Planner
================================
Implements Oracle 11g sequence-plus-trigger fallback emulation metadata planning.
"""

from typing import Optional, Tuple
from akaal.migration.models import ObjectType
from akaal.migration.ddl.planning.models import (
    TriggerFallbackPlan,
    PlanReadinessStatus,
    ObjectIdentity,
    ObjectInventory
)
from akaal.migration.ddl.planning.naming import generate_fallback_name, DatabaseDialect


class OracleTriggerFallbackPlanner:
    """Plans Oracle 11g insert trigger emulations for identity semantics."""

    @staticmethod
    def plan_trigger(
        schema: str,
        table: str,
        column: str,
        referenced_sequence: ObjectIdentity,
        mode: str,  # "ALWAYS" or "DEFAULT"
        inventory: ObjectInventory,
        existing_trig_name: Optional[str] = None,
        is_akaal_managed: bool = False
    ) -> Tuple[Optional[TriggerFallbackPlan], PlanReadinessStatus, str]:
        """
        Plans the trigger template mapping and determines compatibility and approval status.
        """
        # Resolve trigger name
        if existing_trig_name:
            trig_name = existing_trig_name
        else:
            trig_name, _ = generate_fallback_name(
                DatabaseDialect.ORACLE, "11.2", schema, table, column, "trg", inventory=inventory
            )
            
        trig_id = ObjectIdentity(schema=schema, name=trig_name, object_type=ObjectType.TRIGGER)

        # 1. Conflict checking on existing trigger names
        if trig_id in inventory.inventory_map:
            if is_akaal_managed:
                # Existing equivalent Akaal-managed trigger -> READY (Reused)
                plan = TriggerFallbackPlan(
                    identity=trig_id,
                    referenced_sequence=referenced_sequence,
                    timing="BEFORE",
                    event="INSERT"
                )
                return plan, PlanReadinessStatus.READY, "Existing Akaal-managed trigger successfully reused."
            else:
                # User-managed trigger conflict
                return None, PlanReadinessStatus.BLOCKED_UNSAFE, f"Conflicting user-managed trigger '{trig_name}' already exists on insert."

        # 2. Render from controlled templates
        # Timing = BEFORE, Event = INSERT
        # Invariant checks: Timing must be BEFORE, Event must be INSERT
        plan = TriggerFallbackPlan(
            identity=trig_id,
            referenced_sequence=referenced_sequence,
            timing="BEFORE",
            event="INSERT"
        )

        # 3. Semantic Mode analysis
        if mode == "ALWAYS":
            # Overwrite behavior represents semantic loss since native rejection cannot be emulated
            return plan, PlanReadinessStatus.REQUIRES_APPROVAL, "GENERATED ALWAYS emulation has semantic overwrite loss. Approval required."
        elif mode == "DEFAULT":
            # Fully compatible approximation
            return plan, PlanReadinessStatus.READY, "GENERATED BY DEFAULT trigger fallback successfully planned."

        return plan, PlanReadinessStatus.READY, "Oracle trigger fallback successfully planned."
