"""
Akaal Enterprise Distributed Runtime (Platform 2).
Provides distributed worker scheduling, task queues, lease management, health aggregation,
and fault tolerance across cluster nodes.
"""

from akaal.distributed.clock.clock import Clock, SystemClock, TestClock
from akaal.distributed.domain.identifiers import (
    WorkerId,
    NodeId,
    ClusterId,
    TaskId,
    ExecutionId,
    AttemptId,
    LeaseId,
    CorrelationId,
    ReservationId,
    IdempotencyKey,
)
from akaal.distributed.domain.enums import (
    WorkerStatus,
    WorkerHealth,
    ClusterState,
    ClusterHealthStatus,
    AssignmentState,
    FailureType,
)
from akaal.distributed.domain.errors import (
    DistributedRuntimeError,
    DomainValidationError,
    WorkerUnavailableError,
    SchedulerError,
    LeaderElectionError,
    DiscoveryError,
    CoordinationError,
    LeaseExpiredError,
    MembershipError,
    ClusterStateError,
    ResourceLimitError,
    TaskDistributionError,
)
from akaal.distributed.domain.models import (
    WorkerCapability,
    CustomResource,
    ResourceSnapshot,
    ResourceReservation,
    Worker,
    Node,
    Cluster,
    Task,
    Lease,
    ExecutionToken,
    Assignment,
    ExecutionRequest,
    ExecutionResult,
    Heartbeat,
    ClusterMembership,
    SchedulerDecision,
    ClusterSnapshot,
)
from akaal.distributed.events.events import (
    EventMetadata,
    DistributedDomainEvent,
    WorkerRegistered,
    WorkerRemoved,
    WorkerHeartbeatEvent,
    WorkerUnavailable,
    LeaderChanged,
    TaskQueued,
    TaskAssigned,
    TaskLeased,
    TaskStarted,
    TaskCompleted,
    TaskFailed,
    TaskRetried,
    LeaseExpired,
    WorkerScaled,
    ClusterRecovered,
    ClusterDegraded,
    ConfigReloaded,
    EventPublisher,
    EventSubscriber,
    InProcessEventDispatcher,
)
from akaal.distributed.repository.interfaces import (
    WorkerRepository,
    ClusterRepository,
    TaskRepository,
    LeaseRepository,
    MembershipRepository,
)
from akaal.distributed.repository.state_store import ClusterStateStore
from akaal.distributed.repository.memory_repository import (
    InMemoryWorkerRepository,
    InMemoryClusterRepository,
    InMemoryTaskRepository,
    InMemoryLeaseRepository,
    InMemoryMembershipRepository,
)
from akaal.distributed.coordination.coordinator import CoordinatorService
from akaal.distributed.queue.queue import TaskQueue, MemoryTaskQueue
from akaal.distributed.execution.lifecycle import ExecutionLifecycleManager
from akaal.distributed.execution.recovery import RecoveryManager
from akaal.distributed.cluster.membership import ClusterMembershipService
from akaal.distributed.cluster.leader import ElectionService, LeadershipService
from akaal.distributed.cluster.state_machine import ClusterStateMachine
from akaal.distributed.cluster.health import ClusterHealthService
from akaal.distributed.worker.registry import WorkerRegistry
from akaal.distributed.worker.discovery import DiscoveryService
from akaal.distributed.worker.heartbeat import HeartbeatManager
from akaal.distributed.worker.lease import LeaseManager
from akaal.distributed.scheduler.policy import (
    SchedulingPolicy,
    FIFOSchedulingPolicy,
    PrioritySchedulingPolicy,
    LeastLoadedSchedulingPolicy,
    ResourceAwareSchedulingPolicy,
    AffinitySchedulingPolicy,
    AntiAffinitySchedulingPolicy,
    LocalityAwareSchedulingPolicy,
    FairSchedulingPolicy,
    AdaptiveSchedulingPolicy,
    WeightedSchedulingPolicy,
)
from akaal.distributed.scheduler.selector import WorkerSelector
from akaal.distributed.scheduler.scheduler import ClusterScheduler
from akaal.distributed.resource.manager import ResourceManager
from akaal.distributed.resource.scaling import WorkerScalingManager
from akaal.distributed.engine.distributed_engine import (
    DistributedExecutionEngineV1,
    DefaultDistributedExecutionEngineV1,
)
from akaal.distributed.facade.runtime import (
    DistributedRuntimeV1,
    DefaultDistributedRuntimeV1,
)
from akaal.distributed.config.config import (
    FrozenDistributedConfiguration,
    DistributedRuntimeConfiguration,
)
from akaal.distributed.metrics.metrics import (
    DistributedMetricsCollector,
    InMemoryDistributedMetricsCollector,
)

__all__ = [
    "Clock",
    "SystemClock",
    "TestClock",
    "WorkerId",
    "NodeId",
    "ClusterId",
    "TaskId",
    "ExecutionId",
    "AttemptId",
    "LeaseId",
    "CorrelationId",
    "ReservationId",
    "IdempotencyKey",
    "WorkerStatus",
    "WorkerHealth",
    "ClusterState",
    "ClusterHealthStatus",
    "AssignmentState",
    "FailureType",
    "DistributedRuntimeError",
    "DomainValidationError",
    "WorkerUnavailableError",
    "SchedulerError",
    "LeaderElectionError",
    "DiscoveryError",
    "CoordinationError",
    "LeaseExpiredError",
    "MembershipError",
    "ClusterStateError",
    "ResourceLimitError",
    "TaskDistributionError",
    "WorkerCapability",
    "CustomResource",
    "ResourceSnapshot",
    "ResourceReservation",
    "Worker",
    "Node",
    "Cluster",
    "Task",
    "Lease",
    "ExecutionToken",
    "Assignment",
    "ExecutionRequest",
    "ExecutionResult",
    "Heartbeat",
    "ClusterMembership",
    "SchedulerDecision",
    "ClusterSnapshot",
    "EventMetadata",
    "DistributedDomainEvent",
    "WorkerRegistered",
    "WorkerRemoved",
    "WorkerHeartbeatEvent",
    "WorkerUnavailable",
    "LeaderChanged",
    "TaskQueued",
    "TaskAssigned",
    "TaskLeased",
    "TaskStarted",
    "TaskCompleted",
    "TaskFailed",
    "TaskRetried",
    "LeaseExpired",
    "WorkerScaled",
    "ClusterRecovered",
    "ClusterDegraded",
    "ConfigReloaded",
    "EventPublisher",
    "EventSubscriber",
    "InProcessEventDispatcher",
    "WorkerRepository",
    "ClusterRepository",
    "TaskRepository",
    "LeaseRepository",
    "MembershipRepository",
    "ClusterStateStore",
    "InMemoryWorkerRepository",
    "InMemoryClusterRepository",
    "InMemoryTaskRepository",
    "InMemoryLeaseRepository",
    "InMemoryMembershipRepository",
    "CoordinatorService",
    "TaskQueue",
    "MemoryTaskQueue",
    "ExecutionLifecycleManager",
    "RecoveryManager",
    "ClusterMembershipService",
    "ElectionService",
    "LeadershipService",
    "ClusterStateMachine",
    "ClusterHealthService",
    "WorkerRegistry",
    "DiscoveryService",
    "HeartbeatManager",
    "LeaseManager",
    "SchedulingPolicy",
    "FIFOSchedulingPolicy",
    "PrioritySchedulingPolicy",
    "LeastLoadedSchedulingPolicy",
    "ResourceAwareSchedulingPolicy",
    "AffinitySchedulingPolicy",
    "AntiAffinitySchedulingPolicy",
    "LocalityAwareSchedulingPolicy",
    "FairSchedulingPolicy",
    "AdaptiveSchedulingPolicy",
    "WeightedSchedulingPolicy",
    "WorkerSelector",
    "ClusterScheduler",
    "ResourceManager",
    "WorkerScalingManager",
    "DistributedExecutionEngineV1",
    "DefaultDistributedExecutionEngineV1",
    "DistributedRuntimeV1",
    "DefaultDistributedRuntimeV1",
    "FrozenDistributedConfiguration",
    "DistributedRuntimeConfiguration",
    "DistributedMetricsCollector",
    "InMemoryDistributedMetricsCollector",
]
