"""
Distributed Events package.
"""

from akaal.distributed.events.events import (
    EventMetadata,
    DistributedDomainEvent,
    WorkerRegistered,
    WorkerRemoved,
    WorkerHeartbeatEvent,
    WorkerUnavailable,
    LeaderChanged,
    TaskQueued,
    TaskAssigned,
    TaskLeased,
    TaskStarted,
    TaskCompleted,
    TaskFailed,
    TaskRetried,
    LeaseExpired,
    WorkerScaled,
    ClusterRecovered,
    ClusterDegraded,
    ConfigReloaded,
    EventPublisher,
    EventSubscriber,
    InProcessEventDispatcher,
)

__all__ = [
    "EventMetadata",
    "DistributedDomainEvent",
    "WorkerRegistered",
    "WorkerRemoved",
    "WorkerHeartbeatEvent",
    "WorkerUnavailable",
    "LeaderChanged",
    "TaskQueued",
    "TaskAssigned",
    "TaskLeased",
    "TaskStarted",
    "TaskCompleted",
    "TaskFailed",
    "TaskRetried",
    "LeaseExpired",
    "WorkerScaled",
    "ClusterRecovered",
    "ClusterDegraded",
    "ConfigReloaded",
    "EventPublisher",
    "EventSubscriber",
    "InProcessEventDispatcher",
]
