import {
  ProjectDiscoveryItem,
  InitiativeDiscoveryItem,
  PortfolioAttentionItem,
  ProjectsPortfolioSummary,
  InitiativeWorkspaceDetail,
  InitiativeActivityItem
} from './projects.models';

/**
 * Isolated Hostile Matrix Fixtures (Strictly for Unit & Integration Testing)
 * None of these are baked into production runtime state.
 */

// 1. STANDARD READY STATE
export const FIXTURE_STANDARD_INITIATIVES: InitiativeDiscoveryItem[] = [
  {
    id: 'init-dc-exit-2027',
    key: 'DC-EXIT-2027',
    name: 'Data Center Exit & Modernization 2027',
    objective: 'Migrate on-premise relational and legacy warehouse footprints to managed multi-cloud infrastructure.',
    description: 'Consolidated modernization program covering Oracle, DB2, and SQL Server legacy estates.',
    status: 'ACTIVE',
    associatedProjectIds: ['proj-core-banking', 'proj-payments-gw', 'proj-db2-retirement'],
    associatedProjectCount: 3,
    associatedProjectsSummary: [
      { id: 'proj-core-banking', key: 'CB-MOD', name: 'Core Banking Ledger Modernization' },
      { id: 'proj-payments-gw', key: 'PAY-GW', name: 'Payments Gateway Real-Time Sync' },
      { id: 'proj-db2-retirement', key: 'DB2-RET', name: 'Mainframe DB2 Warehouse Retirement' }
    ],
    lastActivityAt: '2026-09-07T14:30:00Z',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-09-07T14:30:00Z',
    backendAvailability: 'READY',
    accessState: 'GRANTED'
  },
  {
    id: 'init-analytics-cloud',
    key: 'ANALYTICS-2026',
    name: 'Unified Cloud Analytics Platform',
    objective: 'Establish enterprise Snowflake & BigQuery lakehouse fed by continuous CDC streams.',
    description: 'Cross-functional data ingestion program for real-time reporting and fraud intelligence.',
    status: 'ACTIVE',
    associatedProjectIds: ['proj-c360-ingest', 'proj-fraud-stream'],
    associatedProjectCount: 2,
    associatedProjectsSummary: [
      { id: 'proj-c360-ingest', key: 'C360-ING', name: 'Customer 360 Lakehouse Ingestion' },
      { id: 'proj-fraud-stream', key: 'FRD-CDC', name: 'Fraud Telemetry Continuous Streaming' }
    ],
    lastActivityAt: '2026-09-07T11:15:00Z',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-09-07T11:15:00Z',
    backendAvailability: 'READY',
    accessState: 'GRANTED'
  },
  {
    id: 'init-compliance-archival',
    key: 'COMP-ARCH-2026',
    name: 'Regulatory Long-Term Archival',
    objective: 'Move cold audit tables and immutable financial ledgers to encrypted object storage.',
    description: 'Mandatory FINRA and GDPR long-term retention lifecycle migration.',
    status: 'PLANNING',
    associatedProjectIds: ['proj-audit-archive'],
    associatedProjectCount: 1,
    associatedProjectsSummary: [
      { id: 'proj-audit-archive', key: 'AUD-ARC', name: 'Historical Audit Ledger Archival' }
    ],
    lastActivityAt: '2026-09-06T18:00:00Z',
    createdAt: '2026-05-10T14:00:00Z',
    updatedAt: '2026-09-06T18:00:00Z',
    backendAvailability: 'READY',
    accessState: 'GRANTED'
  }
];

export const FIXTURE_STANDARD_PROJECTS: ProjectDiscoveryItem[] = [
  {
    id: 'proj-core-banking',
    key: 'CB-MOD',
    name: 'Core Banking Ledger Modernization',
    description: 'Mission-critical Oracle 19c RAC to AWS Aurora PostgreSQL 16 migration with active-active validation.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-dc-exit-2027',
    initiativeName: 'Data Center Exit & Modernization 2027',
    initiativeKey: 'DC-EXIT-2027',
    status: 'ACTIVE',
    migrationCount: 8,
    validationCount: 4,
    activeWorkloadsCount: 3,
    attentionCount: 1,
    lastActivityAt: '2026-09-07T14:30:00Z',
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-09-07T14:30:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  {
    id: 'proj-payments-gw',
    key: 'PAY-GW',
    name: 'Payments Gateway Real-Time Sync',
    description: 'Continuous Kafka-driven change data capture synchronization for settlement engines.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-dc-exit-2027',
    initiativeName: 'Data Center Exit & Modernization 2027',
    initiativeKey: 'DC-EXIT-2027',
    status: 'ACTIVE',
    migrationCount: 4,
    validationCount: 2,
    activeWorkloadsCount: 2,
    attentionCount: 0,
    lastActivityAt: '2026-09-07T13:45:00Z',
    createdAt: '2026-02-15T11:00:00Z',
    updatedAt: '2026-09-07T13:45:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  {
    id: 'proj-c360-ingest',
    key: 'C360-ING',
    name: 'Customer 360 Lakehouse Ingestion',
    description: 'Bulk snapshot and delta synchronization into Snowflake enterprise data warehouse.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-analytics-cloud',
    initiativeName: 'Unified Cloud Analytics Platform',
    initiativeKey: 'ANALYTICS-2026',
    status: 'ACTIVE',
    migrationCount: 12,
    validationCount: 6,
    activeWorkloadsCount: 4,
    attentionCount: 0,
    lastActivityAt: '2026-09-07T11:15:00Z',
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-09-07T11:15:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  {
    id: 'proj-fraud-stream',
    key: 'FRD-CDC',
    name: 'Fraud Telemetry Continuous Streaming',
    description: 'Low-latency CDC pipeline from transactional databases into Google Cloud BigQuery.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-analytics-cloud',
    initiativeName: 'Unified Cloud Analytics Platform',
    initiativeKey: 'ANALYTICS-2026',
    status: 'ACTIVE',
    migrationCount: 3,
    validationCount: 1,
    activeWorkloadsCount: 1,
    attentionCount: 0,
    lastActivityAt: '2026-09-07T09:20:00Z',
    createdAt: '2026-04-05T09:30:00Z',
    updatedAt: '2026-09-07T09:20:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  {
    id: 'proj-db2-retirement',
    key: 'DB2-RET',
    name: 'Mainframe DB2 Warehouse Retirement',
    description: 'High-volume historical data extraction from mainframe z/OS DB2 into Azure SQL Managed Instance.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-dc-exit-2027',
    initiativeName: 'Data Center Exit & Modernization 2027',
    initiativeKey: 'DC-EXIT-2027',
    status: 'PLANNING',
    migrationCount: 6,
    validationCount: 0,
    activeWorkloadsCount: 0,
    attentionCount: 0,
    lastActivityAt: '2026-09-06T16:00:00Z',
    createdAt: '2026-04-20T14:00:00Z',
    updatedAt: '2026-09-06T16:00:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  {
    id: 'proj-audit-archive',
    key: 'AUD-ARC',
    name: 'Historical Audit Ledger Archival',
    description: 'Parquet export and checksum verification of 7-year audit logs to AWS S3 Glacier Vault.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-compliance-archival',
    initiativeName: 'Regulatory Long-Term Archival',
    initiativeKey: 'COMP-ARCH-2026',
    status: 'PLANNING',
    migrationCount: 2,
    validationCount: 1,
    activeWorkloadsCount: 0,
    attentionCount: 0,
    lastActivityAt: '2026-09-06T18:00:00Z',
    createdAt: '2026-05-15T15:00:00Z',
    updatedAt: '2026-09-06T18:00:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  }
];

export const FIXTURE_STANDARD_ATTENTION: PortfolioAttentionItem[] = [
  {
    id: 'att-01',
    title: 'Schema constraint discrepancy detected during validation',
    description: 'Foreign key index mismatch on public.account_ledger between Oracle source and PostgreSQL target.',
    severity: 'WARNING',
    occurredAt: '2026-09-07T14:15:00Z',
    category: 'VALIDATION_FINDING',
    projectId: 'proj-core-banking',
    projectName: 'Core Banking Ledger Modernization',
    migrationId: 'mig-cb-01',
    migrationName: 'Accounts & General Ledger M2 Migration',
    actionLabel: 'Investigate in Validation Studio',
    actionRoute: '/migration/validation/val-mission-11'
  }
];

export const FIXTURE_STANDARD_SUMMARY: ProjectsPortfolioSummary = {
  totalProjects: 6,
  activeProjects: 4,
  totalInitiatives: 3,
  activeInitiatives: 2,
  attentionCount: 1
};

// ============================================================================
// PART B: INITIATIVE WORKSPACE & ACTIVITY FIXTURES
// ============================================================================

export const FIXTURE_INITIATIVE_WORKSPACES: Record<string, InitiativeWorkspaceDetail> = {
  'init-dc-exit-2027': {
    id: 'init-dc-exit-2027',
    key: 'DC-EXIT-2027',
    name: 'Data Center Exit & Modernization 2027',
    objective: 'Migrate on-premise relational and legacy warehouse footprints to managed multi-cloud infrastructure.',
    description: 'Consolidated modernization program covering Oracle, DB2, and SQL Server legacy estates across EMEA data centers.',
    status: 'ACTIVE',
    associatedProjectIds: ['proj-core-banking', 'proj-payments-gw', 'proj-db2-retirement'],
    totalProjectsCount: 3,
    activeProjectsCount: 2,
    workloadsCount: 18,
    attentionCount: 1,
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-09-07T14:30:00Z',
    lastActivityAt: '2026-09-07T14:30:00Z',
    backendAvailability: 'READY',
    accessState: 'GRANTED'
  },
  'init-analytics-cloud': {
    id: 'init-analytics-cloud',
    key: 'ANALYTICS-2026',
    name: 'Unified Cloud Analytics Platform',
    objective: 'Establish enterprise Snowflake & BigQuery lakehouse fed by continuous CDC streams.',
    description: 'Cross-functional data ingestion program for real-time reporting and fraud intelligence.',
    status: 'ACTIVE',
    associatedProjectIds: ['proj-c360-ingest', 'proj-fraud-stream'],
    totalProjectsCount: 2,
    activeProjectsCount: 2,
    workloadsCount: 15,
    attentionCount: 0,
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-09-07T11:15:00Z',
    lastActivityAt: '2026-09-07T11:15:00Z',
    backendAvailability: 'READY',
    accessState: 'GRANTED'
  },
  'init-compliance-archival': {
    id: 'init-compliance-archival',
    key: 'COMP-ARCH-2026',
    name: 'Regulatory Long-Term Archival',
    objective: 'Move cold audit tables and immutable financial ledgers to encrypted object storage.',
    description: 'Mandatory FINRA and GDPR long-term retention lifecycle migration.',
    status: 'PLANNING',
    associatedProjectIds: ['proj-audit-archive'],
    totalProjectsCount: 1,
    activeProjectsCount: 0,
    workloadsCount: 2,
    attentionCount: 0,
    createdAt: '2026-05-10T14:00:00Z',
    updatedAt: '2026-09-06T18:00:00Z',
    lastActivityAt: '2026-09-06T18:00:00Z',
    backendAvailability: 'READY',
    accessState: 'GRANTED'
  }
};

export const FIXTURE_INITIATIVE_ACTIVITIES: InitiativeActivityItem[] = [
  {
    id: 'act-init-01',
    initiativeId: 'init-dc-exit-2027',
    title: 'Validation Mission #11 Schema Audit Finding',
    description: 'Foreign key discrepancy surfaced in Accounts & General Ledger migration for Core Banking.',
    category: 'MILESTONE',
    severity: 'WARNING',
    occurredAt: '2026-09-07T14:15:00Z',
    actorName: 'Validation Engine',
    subjectName: 'Core Banking Ledger Modernization',
    subjectType: 'PROJECT',
    actionType: 'REVIEW',
    actionRoute: '/migration/validation/val-mission-11'
  },
  {
    id: 'act-init-02',
    initiativeId: 'init-dc-exit-2027',
    title: 'Project Associated with Initiative',
    description: 'Mainframe DB2 Warehouse Retirement was linked to Data Center Exit & Modernization 2027.',
    category: 'ASSOCIATION',
    severity: 'INFO',
    occurredAt: '2026-09-06T16:00:00Z',
    actorName: 'Aalok Ladwa',
    subjectName: 'Mainframe DB2 Warehouse Retirement',
    subjectType: 'PROJECT',
    actionType: 'VIEW'
  },
  {
    id: 'act-init-03',
    initiativeId: 'init-dc-exit-2027',
    title: 'Cutover Gate Approved',
    description: 'Stage 3 Dual-Run replication signoff completed with 4-eyes authorization.',
    category: 'GOVERNANCE',
    severity: 'SUCCESS',
    occurredAt: '2026-09-05T10:30:00Z',
    actorName: 'Security Officer',
    subjectName: 'Payments Gateway Real-Time Sync',
    subjectType: 'MIGRATION',
    actionType: 'VIEW'
  },
  {
    id: 'act-init-04',
    initiativeId: 'init-analytics-cloud',
    title: 'Continuous Streaming Pipeline Initialized',
    description: 'Fraud Telemetry CDC pipeline reached steady-state synchronization with Google Cloud BigQuery.',
    category: 'MILESTONE',
    severity: 'SUCCESS',
    occurredAt: '2026-09-07T09:20:00Z',
    actorName: 'CDC Engine',
    subjectName: 'Fraud Telemetry Continuous Streaming',
    subjectType: 'PROJECT',
    actionType: 'VIEW'
  }
];

// ============================================================================
// PART C: PROJECT WORKSPACE & CREATION FIXTURES
// ============================================================================

export const FIXTURE_AVAILABLE_PRINCIPALS: import('./projects.models').ProjectPrincipal[] = [
  {
    id: 'usr-aalok-ladwa',
    name: 'Aalok Ladwa',
    email: 'aalok.ladwa@enterprise.corp',
    type: 'USER',
    role: 'PROJECT_ADMIN'
  },
  {
    id: 'grp-cloud-engineers',
    name: 'Cloud Migration Engineering Team',
    email: 'cloud-mig-eng@enterprise.corp',
    type: 'GROUP',
    role: 'OPERATOR'
  },
  {
    id: 'grp-data-gov',
    name: 'Enterprise Data Governance Office',
    email: 'data-gov@enterprise.corp',
    type: 'GROUP',
    role: 'VIEWER'
  },
  {
    id: 'sa-pipeline-worker',
    name: 'akaal-pipeline-worker-sa',
    email: 'service-account-pipeline@sys.akaal.internal',
    type: 'SERVICE_ACCOUNT',
    role: 'OPERATOR'
  },
  {
    id: 'usr-sarah-jenkins',
    name: 'Sarah Jenkins (Lead DBA)',
    email: 's.jenkins@enterprise.corp',
    type: 'USER',
    role: 'PROJECT_ADMIN'
  }
];

export const FIXTURE_AVAILABLE_CONNECTIONS: import('./projects.models').ProjectResourceIntent[] = [
  {
    connectionId: 'conn-ora-prod-01',
    connectionName: 'EMEA Core Banking Oracle 19c RAC',
    provider: 'Oracle',
    category: 'RELATIONAL',
    environment: 'Production',
    host: 'ora-rac-01.emea.internal:1521/CORE_LEDGER'
  },
  {
    connectionId: 'conn-pg-aurora-01',
    connectionName: 'AWS Aurora PostgreSQL 16 Cluster',
    provider: 'PostgreSQL',
    category: 'RELATIONAL',
    environment: 'Production',
    host: 'aurora-pg-prod.cluster-xyz.eu-west-1.rds.amazonaws.com:5432/core_ledger'
  },
  {
    connectionId: 'conn-snow-lakehouse',
    connectionName: 'Snowflake Enterprise Data Warehouse',
    provider: 'Snowflake',
    category: 'WAREHOUSE',
    environment: 'Production',
    host: 'ent-org-acc.snowflakecomputing.com:443'
  },
  {
    connectionId: 'conn-kafka-prod',
    connectionName: 'Kafka Settlement Real-Time Event Bus',
    provider: 'Kafka',
    category: 'STREAMING',
    environment: 'Production',
    host: 'kafka-broker-01.prod.internal:9092'
  },
  {
    connectionId: 'conn-bq-analytics',
    connectionName: 'Google Cloud BigQuery Telemetry',
    provider: 'Google BigQuery',
    category: 'WAREHOUSE',
    environment: 'Production',
    host: 'bigquery.googleapis.com/projects/corp-telemetry-prod'
  },
  {
    connectionId: 'conn-db2-zos',
    connectionName: 'Mainframe z/OS DB2 v13 Subsystem',
    provider: 'IBM Db2',
    category: 'RELATIONAL',
    environment: 'Production',
    host: 'mf-db2-subsys.host.internal:50000/HIST_WH'
  }
];

export const FIXTURE_PROJECT_ACTIVITIES: import('./projects.models').InitiativeActivityItem[] = [
  {
    id: 'act-proj-01',
    projectId: 'proj-core-banking',
    title: 'Accounts & Ledger M2 Cutover Readiness Check',
    description: 'Schema parity validated across 142 tables; awaiting 4-eyes security signoff.',
    category: 'VALIDATION',
    severity: 'WARNING',
    occurredAt: '2026-09-07T14:15:00Z',
    actorName: 'Validation Engine',
    subjectName: 'Accounts & General Ledger M2',
    subjectType: 'VALIDATION',
    actionType: 'REVIEW',
    actionRoute: '/migration/validation/val-mission-11'
  },
  {
    id: 'act-proj-02',
    projectId: 'proj-core-banking',
    title: 'Incremental CDC Pipeline Synchronized',
    description: 'CDC streaming reached sub-50ms replication lag on partition chunk 8/12.',
    category: 'EXECUTION',
    severity: 'SUCCESS',
    occurredAt: '2026-09-07T12:00:00Z',
    actorName: 'akaal-pipeline-worker-sa',
    subjectName: 'Core Banking Ledger Modernization',
    subjectType: 'MIGRATION',
    actionType: 'VIEW'
  },
  {
    id: 'act-proj-03',
    projectId: 'proj-core-banking',
    title: 'Connection Profile Associated',
    description: 'AWS Aurora PostgreSQL 16 Cluster added to project resource intent.',
    category: 'METADATA',
    severity: 'INFO',
    occurredAt: '2026-09-06T11:00:00Z',
    actorName: 'Aalok Ladwa',
    subjectName: 'AWS Aurora PostgreSQL 16 Cluster',
    subjectType: 'RESOURCE',
    actionType: 'VIEW'
  },
  {
    id: 'act-proj-04',
    projectId: 'proj-payments-gw',
    title: 'Kafka Consumer Group Rebalance Completed',
    description: 'Payment settlement topic stream successfully attached 6 parallel partitions.',
    category: 'EXECUTION',
    severity: 'SUCCESS',
    occurredAt: '2026-09-07T13:45:00Z',
    actorName: 'Kafka Adapter',
    subjectName: 'Payments Gateway Real-Time Sync',
    subjectType: 'MIGRATION',
    actionType: 'VIEW'
  }
];

export const FIXTURE_PROJECT_WORKSPACES: Record<string, import('./projects.models').ProjectWorkspaceDetail> = {
  'proj-core-banking': {
    id: 'proj-core-banking',
    key: 'CB-MOD',
    name: 'Core Banking Ledger Modernization',
    description: 'Mission-critical Oracle 19c RAC to AWS Aurora PostgreSQL 16 migration with active-active validation and sub-second cutover SLA.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-dc-exit-2027',
    initiativeName: 'Data Center Exit & Modernization 2027',
    initiativeKey: 'DC-EXIT-2027',
    status: 'ACTIVE',
    currentWork: {
      totalMigrations: 8,
      activeMigrations: 3,
      completedMigrations: 5,
      totalValidations: 4,
      passedValidations: 3,
      discrepancyValidations: 1
    },
    upcomingEvents: [
      {
        id: 'evt-01',
        title: 'Stage 3 Dual-Run Verification Window',
        description: 'Scheduled shadow traffic replication and real-time checksum comparison.',
        scheduledAt: '2026-09-12T02:00:00Z',
        type: 'CUTOVER_WINDOW'
      },
      {
        id: 'evt-02',
        title: 'Schema Freeze for General Ledger Cutover',
        description: 'Strict DDL lockdown across source Oracle clusters.',
        scheduledAt: '2026-09-15T00:00:00Z',
        type: 'SCHEMA_FREEZE'
      }
    ],
    recentActivities: FIXTURE_PROJECT_ACTIVITIES.filter(a => a.projectId === 'proj-core-banking'),
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-09-07T14:30:00Z',
    lastActivityAt: '2026-09-07T14:30:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  'proj-payments-gw': {
    id: 'proj-payments-gw',
    key: 'PAY-GW',
    name: 'Payments Gateway Real-Time Sync',
    description: 'Continuous Kafka-driven change data capture synchronization for settlement engines with zero data loss guarantee.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-dc-exit-2027',
    initiativeName: 'Data Center Exit & Modernization 2027',
    initiativeKey: 'DC-EXIT-2027',
    status: 'ACTIVE',
    currentWork: {
      totalMigrations: 4,
      activeMigrations: 2,
      completedMigrations: 2,
      totalValidations: 2,
      passedValidations: 2,
      discrepancyValidations: 0
    },
    upcomingEvents: [
      {
        id: 'evt-03',
        title: 'High-Volume Settlement Stress Test',
        description: 'Replay 100k events/sec peak volume through target pipeline.',
        scheduledAt: '2026-09-14T18:00:00Z',
        type: 'SYNC_BATCH'
      }
    ],
    recentActivities: FIXTURE_PROJECT_ACTIVITIES.filter(a => a.projectId === 'proj-payments-gw'),
    createdAt: '2026-02-15T11:00:00Z',
    updatedAt: '2026-09-07T13:45:00Z',
    lastActivityAt: '2026-09-07T13:45:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  'proj-c360-ingest': {
    id: 'proj-c360-ingest',
    key: 'C360-ING',
    name: 'Customer 360 Lakehouse Ingestion',
    description: 'Bulk snapshot and delta synchronization into Snowflake enterprise data warehouse for real-time customer analytics.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-analytics-cloud',
    initiativeName: 'Unified Cloud Analytics Platform',
    initiativeKey: 'ANALYTICS-2026',
    status: 'ACTIVE',
    currentWork: {
      totalMigrations: 12,
      activeMigrations: 4,
      completedMigrations: 8,
      totalValidations: 6,
      passedValidations: 6,
      discrepancyValidations: 0
    },
    upcomingEvents: [],
    recentActivities: [],
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-09-07T11:15:00Z',
    lastActivityAt: '2026-09-07T11:15:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  'proj-fraud-stream': {
    id: 'proj-fraud-stream',
    key: 'FRD-CDC',
    name: 'Fraud Telemetry Continuous Streaming',
    description: 'Low-latency CDC pipeline from transactional databases into Google Cloud BigQuery for AI anomaly detection.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-analytics-cloud',
    initiativeName: 'Unified Cloud Analytics Platform',
    initiativeKey: 'ANALYTICS-2026',
    status: 'ACTIVE',
    currentWork: {
      totalMigrations: 3,
      activeMigrations: 1,
      completedMigrations: 2,
      totalValidations: 1,
      passedValidations: 1,
      discrepancyValidations: 0
    },
    upcomingEvents: [],
    recentActivities: [],
    createdAt: '2026-04-05T09:30:00Z',
    updatedAt: '2026-09-07T09:20:00Z',
    lastActivityAt: '2026-09-07T09:20:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  'proj-db2-retirement': {
    id: 'proj-db2-retirement',
    key: 'DB2-RET',
    name: 'Mainframe DB2 Warehouse Retirement',
    description: 'High-volume historical data extraction from mainframe z/OS DB2 into Azure SQL Managed Instance.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-dc-exit-2027',
    initiativeName: 'Data Center Exit & Modernization 2027',
    initiativeKey: 'DC-EXIT-2027',
    status: 'PLANNING',
    currentWork: {
      totalMigrations: 6,
      activeMigrations: 0,
      completedMigrations: 0,
      totalValidations: 0,
      passedValidations: 0,
      discrepancyValidations: 0
    },
    upcomingEvents: [],
    recentActivities: [],
    createdAt: '2026-04-20T14:00:00Z',
    updatedAt: '2026-09-06T16:00:00Z',
    lastActivityAt: '2026-09-06T16:00:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  },
  'proj-audit-archive': {
    id: 'proj-audit-archive',
    key: 'AUD-ARC',
    name: 'Historical Audit Ledger Archival',
    description: 'Parquet export and checksum verification of 7-year audit logs to AWS S3 Glacier Vault for compliance.',
    workspaceId: 'ws-prod-emea',
    environmentName: 'Production',
    isProduction: true,
    initiativeId: 'init-compliance-archival',
    initiativeName: 'Regulatory Long-Term Archival',
    initiativeKey: 'COMP-ARCH-2026',
    status: 'PLANNING',
    currentWork: {
      totalMigrations: 2,
      activeMigrations: 0,
      completedMigrations: 0,
      totalValidations: 1,
      passedValidations: 1,
      discrepancyValidations: 0
    },
    upcomingEvents: [],
    recentActivities: [],
    createdAt: '2026-05-15T15:00:00Z',
    updatedAt: '2026-09-06T18:00:00Z',
    lastActivityAt: '2026-09-06T18:00:00Z',
    availability: 'READY',
    accessState: 'GRANTED'
  }
};

// ============================================================================
// PART D: PROJECT WORK (MIGRATIONS + VALIDATIONS + RESOURCES) FIXTURES
// ============================================================================

export const FIXTURE_PROJECT_MIGRATIONS: import('./projects.models').ProjectMigrationItem[] = [
  {
    id: 'mig-cb-01',
    key: 'MIG-CB-01',
    name: 'Accounts & General Ledger M2',
    projectId: 'proj-core-banking',
    projectName: 'Core Banking Ledger Modernization',
    sourceProvider: 'Oracle 19c RAC',
    sourceLabel: 'CORE_LEDGER',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    targetLabel: 'core_ledger',
    mode: 'ONLINE_CDC',
    lifecycleState: 'RUNNING',
    currentPhase: 'Stage 2: Chunk Replication',
    lastActivityAt: '2026-09-07T14:15:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-cb-02',
    key: 'MIG-CB-02',
    name: 'Standing Orders & Mandates Realtime Sync',
    projectId: 'proj-core-banking',
    projectName: 'Core Banking Ledger Modernization',
    sourceProvider: 'Oracle 19c RAC',
    sourceLabel: 'MANDATES_SCHEMA',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    targetLabel: 'mandates_db',
    mode: 'ONLINE_CDC',
    lifecycleState: 'RUNNING',
    currentPhase: 'Stage 3: Dual-Run Sync',
    lastActivityAt: '2026-09-07T13:30:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-cb-03',
    key: 'MIG-CB-03',
    name: 'Customer Reference & KYC History',
    projectId: 'proj-core-banking',
    projectName: 'Core Banking Ledger Modernization',
    sourceProvider: 'Oracle 19c RAC',
    sourceLabel: 'KYC_DATA',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    targetLabel: 'kyc_master',
    mode: 'OFFLINE_BULK',
    lifecycleState: 'COMPLETED',
    currentPhase: 'Completed',
    lastActivityAt: '2026-09-05T18:00:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-cb-04',
    key: 'MIG-CB-04',
    name: 'Debit Card Transactions Historical Batch',
    projectId: 'proj-core-banking',
    projectName: 'Core Banking Ledger Modernization',
    sourceProvider: 'Oracle 19c RAC',
    sourceLabel: 'TX_HIST',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    targetLabel: 'tx_archive',
    mode: 'OFFLINE_BULK',
    lifecycleState: 'COMPLETED',
    currentPhase: 'Completed',
    lastActivityAt: '2026-09-04T12:00:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-cb-05',
    key: 'MIG-CB-05',
    name: 'FX Rates & Daily Positions Mirror',
    projectId: 'proj-core-banking',
    projectName: 'Core Banking Ledger Modernization',
    sourceProvider: 'Oracle 19c RAC',
    sourceLabel: 'FX_ENGINE',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    targetLabel: 'fx_rates',
    mode: 'DUAL_RUN',
    lifecycleState: 'ATTENTION',
    currentPhase: 'Stage 3: Checksum Mismatch',
    lastActivityAt: '2026-09-07T14:15:00Z',
    attentionRequired: true,
    attentionText: 'Schema constraint discrepancy detected during validation',
    availability: 'READY'
  },
  {
    id: 'mig-pay-01',
    key: 'MIG-PAY-01',
    name: 'Payment Settlement Real-Time Stream',
    projectId: 'proj-payments-gw',
    projectName: 'Payments Gateway Real-Time Sync',
    sourceProvider: 'Kafka Cluster',
    sourceLabel: 'payments.settlement.v1',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    targetLabel: 'settlement_feed',
    mode: 'ONLINE_CDC',
    lifecycleState: 'RUNNING',
    currentPhase: 'Stage 2: Continuous Ingestion',
    lastActivityAt: '2026-09-07T13:45:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-pay-02',
    key: 'MIG-PAY-02',
    name: 'ISO 20022 Clearing History Archive',
    projectId: 'proj-payments-gw',
    projectName: 'Payments Gateway Real-Time Sync',
    sourceProvider: 'PostgreSQL 14',
    sourceLabel: 'clearing_archive',
    targetProvider: 'Azure SQL MI',
    targetLabel: 'clearing_wh',
    mode: 'OFFLINE_BULK',
    lifecycleState: 'COMPLETED',
    currentPhase: 'Completed',
    lastActivityAt: '2026-09-06T10:00:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-c360-01',
    key: 'MIG-C360-01',
    name: 'CRM Account Profiles Bulk Load',
    projectId: 'proj-c360-ingest',
    projectName: 'Customer 360 Lakehouse Ingestion',
    sourceProvider: 'Oracle 19c',
    sourceLabel: 'CRM_PROFILES',
    targetProvider: 'Snowflake',
    targetLabel: 'C360_MART',
    mode: 'OFFLINE_BULK',
    lifecycleState: 'COMPLETED',
    currentPhase: 'Completed',
    lastActivityAt: '2026-09-07T11:15:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-c360-02',
    key: 'MIG-C360-02',
    name: 'Product Catalog & Pricing Delta Feed',
    projectId: 'proj-c360-ingest',
    projectName: 'Customer 360 Lakehouse Ingestion',
    sourceProvider: 'Oracle 19c',
    sourceLabel: 'PRICING_CATALOG',
    targetProvider: 'Snowflake',
    targetLabel: 'CATALOG_STAGING',
    mode: 'ONLINE_CDC',
    lifecycleState: 'RUNNING',
    currentPhase: 'Stage 2: Stream Ingest',
    lastActivityAt: '2026-09-07T10:00:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-frd-01',
    key: 'MIG-FRD-01',
    name: 'Card Auth Anomaly Events Feed',
    projectId: 'proj-fraud-stream',
    projectName: 'Fraud Telemetry Continuous Streaming',
    sourceProvider: 'PostgreSQL 15',
    sourceLabel: 'auth_stream',
    targetProvider: 'Google BigQuery',
    targetLabel: 'telemetry_dataset',
    mode: 'ONLINE_CDC',
    lifecycleState: 'RUNNING',
    currentPhase: 'Stage 2: Real-Time Stream',
    lastActivityAt: '2026-09-07T09:20:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-db2-01',
    key: 'MIG-DB2-01',
    name: 'Mainframe Ledger Partition 1990-2005',
    projectId: 'proj-db2-retirement',
    projectName: 'Mainframe DB2 Warehouse Retirement',
    sourceProvider: 'IBM Db2 z/OS',
    sourceLabel: 'HIST_WH.LEDGER_90_05',
    targetProvider: 'Azure SQL MI',
    targetLabel: 'legacy_archive',
    mode: 'OFFLINE_BULK',
    lifecycleState: 'PLANNING',
    currentPhase: 'Stage 0: Pre-Flight Planning',
    lastActivityAt: '2026-09-06T16:00:00Z',
    attentionRequired: false,
    availability: 'READY'
  },
  {
    id: 'mig-aud-01',
    key: 'MIG-AUD-01',
    name: 'FINRA 7-Year Cold Audit Archive',
    projectId: 'proj-audit-archive',
    projectName: 'Historical Audit Ledger Archival',
    sourceProvider: 'PostgreSQL 14',
    sourceLabel: 'audit_logs',
    targetProvider: 'AWS S3 Glacier Vault',
    targetLabel: 'corp-archive-vault',
    mode: 'OFFLINE_BULK',
    lifecycleState: 'PLANNING',
    currentPhase: 'Stage 0: Scope Definition',
    lastActivityAt: '2026-09-06T18:00:00Z',
    attentionRequired: false,
    availability: 'READY'
  }
];

export const FIXTURE_PROJECT_VALIDATIONS: import('./projects.models').ProjectValidationItem[] = [
  {
    id: 'val-cb-01',
    key: 'VAL-CB-01',
    name: 'Val Mission #11: Core Ledger Schema & Foreign Key Audit',
    projectId: 'proj-core-banking',
    projectName: 'Core Banking Ledger Modernization',
    migrationId: 'mig-cb-01',
    migrationName: 'Accounts & General Ledger M2',
    scopeName: 'public.account_ledger',
    sourceProvider: 'Oracle 19c RAC',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    strategy: 'Structural',
    state: 'ATTENTION',
    outcome: 'Discrepancies Found',
    discrepancyCount: 1,
    lastRunAt: '2026-09-07T14:15:00Z',
    availability: 'READY'
  },
  {
    id: 'val-cb-02',
    key: 'VAL-CB-02',
    name: 'Val Mission #08: Customer Balances Reconciliation',
    projectId: 'proj-core-banking',
    projectName: 'Core Banking Ledger Modernization',
    migrationId: 'mig-cb-02',
    migrationName: 'Standing Orders & Mandates Realtime Sync',
    scopeName: 'public.customer_balances',
    sourceProvider: 'Oracle 19c RAC',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    strategy: 'Complete Attribute',
    state: 'COMPLETED',
    outcome: 'Validated',
    discrepancyCount: 0,
    lastRunAt: '2026-09-06T19:00:00Z',
    availability: 'READY'
  },
  {
    id: 'val-cb-03',
    key: 'VAL-CB-03',
    name: 'Val Mission #04: Audit Trail Partition Fingerprint',
    projectId: 'proj-core-banking',
    projectName: 'Core Banking Ledger Modernization',
    migrationId: 'mig-cb-03',
    migrationName: 'Customer Reference & KYC History',
    scopeName: 'public.audit_log',
    sourceProvider: 'Oracle 19c RAC',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    strategy: 'Partition Fingerprint',
    state: 'COMPLETED',
    outcome: 'Validated',
    discrepancyCount: 0,
    lastRunAt: '2026-09-05T18:00:00Z',
    availability: 'READY'
  },
  {
    id: 'val-pay-01',
    key: 'VAL-PAY-01',
    name: 'Val Mission #09: Settlement Stream Packet Counter',
    projectId: 'proj-payments-gw',
    projectName: 'Payments Gateway Real-Time Sync',
    migrationId: 'mig-pay-01',
    migrationName: 'Payment Settlement Real-Time Stream',
    scopeName: 'topics.payments_settled',
    sourceProvider: 'Kafka Cluster',
    targetProvider: 'AWS Aurora PostgreSQL 16',
    strategy: 'Cardinality',
    state: 'RUNNING',
    outcome: 'Running',
    lastRunAt: '2026-09-07T13:45:00Z',
    availability: 'READY'
  },
  {
    id: 'val-pay-02',
    key: 'VAL-PAY-02',
    name: 'Val Mission #05: Clearing Message Schema Verification',
    projectId: 'proj-payments-gw',
    projectName: 'Payments Gateway Real-Time Sync',
    migrationId: 'mig-pay-02',
    migrationName: 'ISO 20022 Clearing History Archive',
    scopeName: 'public.clearing_records',
    sourceProvider: 'PostgreSQL 14',
    targetProvider: 'Azure SQL MI',
    strategy: 'Structural',
    state: 'COMPLETED',
    outcome: 'Validated',
    discrepancyCount: 0,
    lastRunAt: '2026-09-06T10:00:00Z',
    availability: 'READY'
  },
  {
    id: 'val-c360-01',
    key: 'VAL-C360-01',
    name: 'Val Mission #07: Snowflake Table Parity Check',
    projectId: 'proj-c360-ingest',
    projectName: 'Customer 360 Lakehouse Ingestion',
    migrationId: 'mig-c360-01',
    migrationName: 'CRM Account Profiles Bulk Load',
    scopeName: 'C360_MART.ACCOUNTS',
    sourceProvider: 'Oracle 19c',
    targetProvider: 'Snowflake',
    strategy: 'Complete Attribute',
    state: 'COMPLETED',
    outcome: 'Validated',
    discrepancyCount: 0,
    lastRunAt: '2026-09-07T11:15:00Z',
    availability: 'READY'
  },
  {
    id: 'val-frd-01',
    key: 'VAL-FRD-01',
    name: 'Val Mission #06: BigQuery Event Stream Validation',
    projectId: 'proj-fraud-stream',
    projectName: 'Fraud Telemetry Continuous Streaming',
    migrationId: 'mig-frd-01',
    migrationName: 'Card Auth Anomaly Events Feed',
    scopeName: 'telemetry_dataset.fraud_events',
    sourceProvider: 'PostgreSQL 15',
    targetProvider: 'Google BigQuery',
    strategy: 'Cardinality',
    state: 'RUNNING',
    outcome: 'Running',
    lastRunAt: '2026-09-07T09:20:00Z',
    availability: 'READY'
  },
  {
    id: 'val-aud-01',
    key: 'VAL-AUD-01',
    name: 'Val Mission #02: Glacier Hash Checksum Pre-Flight',
    projectId: 'proj-audit-archive',
    projectName: 'Historical Audit Ledger Archival',
    migrationId: 'mig-aud-01',
    migrationName: 'FINRA 7-Year Cold Audit Archive',
    scopeName: 'compliance.glacier_manifest',
    sourceProvider: 'PostgreSQL 14',
    targetProvider: 'AWS S3 Glacier Vault',
    strategy: 'Structural',
    state: 'SCHEDULED',
    outcome: 'Scheduled',
    nextRunAt: '2026-09-15T00:00:00Z',
    availability: 'READY'
  }
];

export const FIXTURE_PROJECT_RESOURCES: import('./projects.models').ProjectResourceItem[] = [
  {
    id: 'res-01',
    connectionId: 'conn-ora-prod-01',
    connectionName: 'EMEA Core Banking Oracle 19c RAC',
    provider: 'Oracle',
    category: 'RELATIONAL',
    environment: 'Production',
    isProduction: true,
    host: 'ora-rac-01.emea.internal:1521/CORE_LEDGER',
    isBoundToProject: true,
    availabilityState: 'BOUND',
    capabilityText: 'CDC LogMiner Enabled • Read/Write Verified',
    lastVerifiedAt: '2026-09-07T14:00:00Z',
    assignedProjectIds: ['proj-core-banking', 'proj-c360-ingest'],
    availability: 'READY'
  },
  {
    id: 'res-02',
    connectionId: 'conn-pg-aurora-01',
    connectionName: 'AWS Aurora PostgreSQL 16 Cluster',
    provider: 'PostgreSQL',
    category: 'RELATIONAL',
    environment: 'Production',
    isProduction: true,
    host: 'aurora-pg-prod.cluster-xyz.eu-west-1.rds.amazonaws.com:5432/core_ledger',
    isBoundToProject: true,
    availabilityState: 'BOUND',
    capabilityText: 'Logical Replication Subscriptions Active',
    lastVerifiedAt: '2026-09-07T14:10:00Z',
    assignedProjectIds: ['proj-core-banking', 'proj-payments-gw'],
    availability: 'READY'
  },
  {
    id: 'res-03',
    connectionId: 'conn-snow-lakehouse',
    connectionName: 'Snowflake Enterprise Data Warehouse',
    provider: 'Snowflake',
    category: 'WAREHOUSE',
    environment: 'Production',
    isProduction: true,
    host: 'ent-org-acc.snowflakecomputing.com:443',
    isBoundToProject: false,
    availabilityState: 'AVAILABLE',
    capabilityText: 'Snowpipe Streaming Enabled',
    lastVerifiedAt: '2026-09-07T11:00:00Z',
    assignedProjectIds: ['proj-c360-ingest'],
    availability: 'READY'
  },
  {
    id: 'res-04',
    connectionId: 'conn-kafka-prod',
    connectionName: 'Kafka Settlement Real-Time Event Bus',
    provider: 'Kafka',
    category: 'STREAMING',
    environment: 'Production',
    isProduction: true,
    host: 'kafka-broker-01.prod.internal:9092',
    isBoundToProject: true,
    availabilityState: 'BOUND',
    capabilityText: 'Schema Registry Linked • SASL_SSL Active',
    lastVerifiedAt: '2026-09-07T13:30:00Z',
    assignedProjectIds: ['proj-core-banking', 'proj-payments-gw'],
    availability: 'READY'
  },
  {
    id: 'res-05',
    connectionId: 'conn-bq-analytics',
    connectionName: 'Google Cloud BigQuery Telemetry',
    provider: 'Google BigQuery',
    category: 'WAREHOUSE',
    environment: 'Production',
    isProduction: true,
    host: 'bigquery.googleapis.com/projects/corp-telemetry-prod',
    isBoundToProject: false,
    availabilityState: 'AVAILABLE',
    capabilityText: 'Storage Write API Active',
    lastVerifiedAt: '2026-09-07T09:00:00Z',
    assignedProjectIds: ['proj-fraud-stream'],
    availability: 'READY'
  },
  {
    id: 'res-06',
    connectionId: 'conn-db2-zos',
    connectionName: 'Mainframe z/OS DB2 v13 Subsystem',
    provider: 'IBM Db2',
    category: 'RELATIONAL',
    environment: 'Production',
    isProduction: true,
    host: 'mf-db2-subsys.host.internal:50000/HIST_WH',
    isBoundToProject: false,
    availabilityState: 'AVAILABLE',
    capabilityText: 'Bulk Extract License Verified',
    lastVerifiedAt: '2026-09-06T15:30:00Z',
    assignedProjectIds: ['proj-db2-retirement'],
    availability: 'READY'
  },
  {
    id: 'res-07',
    connectionId: 'conn-s3-glacier',
    connectionName: 'AWS S3 Glacier Vault',
    provider: 'AWS S3',
    category: 'OBJECT_STORE',
    environment: 'Production',
    isProduction: true,
    host: 's3.eu-west-1.amazonaws.com/corp-archive-vault',
    isBoundToProject: false,
    availabilityState: 'AVAILABLE',
    capabilityText: 'Object Lock Compliance Mode Enabled',
    lastVerifiedAt: '2026-09-06T17:00:00Z',
    assignedProjectIds: ['proj-audit-archive'],
    availability: 'READY'
  },
  {
    id: 'res-08',
    connectionId: 'conn-legacy-unauth',
    connectionName: 'Restricted Sybase ASE Compliance Store',
    provider: 'Sybase ASE',
    category: 'RELATIONAL',
    environment: 'Production',
    isProduction: true,
    host: 'sybase-legacy.corp.internal:5000',
    isBoundToProject: false,
    availabilityState: 'UNAUTHORIZED',
    capabilityText: 'RBAC Policy: Project Operator Role Insufficient',
    lastVerifiedAt: '2026-09-05T08:00:00Z',
    assignedProjectIds: [],
    availability: 'READY'
  },
  {
    id: 'res-09',
    connectionId: 'conn-dr-standby',
    connectionName: 'DR Site Secondary Replica',
    provider: 'Oracle',
    category: 'RELATIONAL',
    environment: 'Production',
    isProduction: true,
    host: 'ora-dr-02.dr.internal:1521/STANDBY',
    isBoundToProject: false,
    availabilityState: 'UNAVAILABLE',
    capabilityText: 'Network Route Unreachable (Standby Inactive)',
    lastVerifiedAt: '2026-09-07T00:00:00Z',
    assignedProjectIds: [],
    availability: 'READY'
  }
];

// ============================================================================
// PART E: PROJECT CONTROL (ACTIVITY, ACCESS, GOVERNANCE, SETTINGS) FIXTURES
// ============================================================================

export const FIXTURE_PROJECT_DETAILED_ACTIVITIES: import('./projects.models').ProjectActivityItem[] = [
  {
    id: 'act-det-01',
    projectId: 'proj-core-banking',
    title: 'Cutover Gate Review Triggered',
    description: 'Stage 3 Dual-Run verification request submitted for multi-party authorization signoff.',
    category: 'GOVERNANCE',
    severity: 'WARNING',
    occurredAt: '2026-09-07T14:30:00Z',
    actorName: 'Aalok Ladwa',
    actorType: 'USER',
    subjectName: 'Accounts & General Ledger M2',
    subjectType: 'GOVERNANCE',
    actionType: 'REVIEW',
    actionRoute: '/migration/projects/proj-core-banking/governance',
    availability: 'READY'
  },
  {
    id: 'act-det-02',
    projectId: 'proj-core-banking',
    title: 'Validation Finding Logged',
    description: 'Schema constraint discrepancy detected during validation on public.account_ledger.',
    category: 'VALIDATION',
    severity: 'WARNING',
    occurredAt: '2026-09-07T14:15:00Z',
    actorName: 'Validation Engine (#11)',
    actorType: 'SYSTEM',
    subjectName: 'Val Mission #11: Core Ledger Schema Audit',
    subjectType: 'VALIDATION',
    actionType: 'REVIEW',
    actionRoute: '/migration/validation/val-mission-11',
    availability: 'READY'
  },
  {
    id: 'act-det-03',
    projectId: 'proj-core-banking',
    title: 'Incremental CDC Pipeline Synchronized',
    description: 'CDC streaming reached sub-50ms replication lag on partition chunk 8/12.',
    category: 'MIGRATION',
    severity: 'SUCCESS',
    occurredAt: '2026-09-07T12:00:00Z',
    actorName: 'akaal-pipeline-worker-sa',
    actorType: 'SERVICE_ACCOUNT',
    subjectName: 'Core Banking Ledger Modernization',
    subjectType: 'MIGRATION',
    actionType: 'VIEW',
    actionRoute: '/migration/cockpit/mig-cb-01',
    availability: 'READY'
  },
  {
    id: 'act-det-04',
    projectId: 'proj-core-banking',
    title: 'Operator Access Granted',
    description: 'Cloud Migration Engineering Team assigned Operator role on project scope.',
    category: 'ACCESS',
    severity: 'INFO',
    occurredAt: '2026-09-06T15:00:00Z',
    actorName: 'Sarah Jenkins',
    actorType: 'USER',
    subjectName: 'Cloud Migration Engineering Team',
    subjectType: 'ACCESS',
    actionType: 'VIEW',
    availability: 'READY'
  },
  {
    id: 'act-det-05',
    projectId: 'proj-core-banking',
    title: 'Connection Profile Bound',
    description: 'AWS Aurora PostgreSQL 16 Cluster associated with project operational intent.',
    category: 'RESOURCE',
    severity: 'INFO',
    occurredAt: '2026-09-06T11:00:00Z',
    actorName: 'Aalok Ladwa',
    actorType: 'USER',
    subjectName: 'AWS Aurora PostgreSQL 16 Cluster',
    subjectType: 'RESOURCE',
    actionType: 'VIEW',
    availability: 'READY'
  },
  {
    id: 'act-det-06',
    projectId: 'proj-core-banking',
    title: 'Project Specification Initialized',
    description: 'Project governance specification established under Data Center Exit & Modernization 2027.',
    category: 'METADATA',
    severity: 'INFO',
    occurredAt: '2026-02-01T08:00:00Z',
    actorName: 'Aalok Ladwa',
    actorType: 'USER',
    subjectName: 'Core Banking Ledger Modernization',
    subjectType: 'PROJECT',
    actionType: 'VIEW',
    availability: 'READY'
  },
  {
    id: 'act-det-07',
    projectId: 'proj-payments-gw',
    title: 'Settlement Topic Stream Bound',
    description: 'Kafka partition group 6 attached with SSL SASL mutual auth confirmation.',
    category: 'MIGRATION',
    severity: 'SUCCESS',
    occurredAt: '2026-09-07T13:45:00Z',
    actorName: 'Kafka Adapter',
    actorType: 'SYSTEM',
    subjectName: 'Payments Gateway Real-Time Sync',
    subjectType: 'MIGRATION',
    actionType: 'VIEW',
    availability: 'READY'
  },
  {
    id: 'act-det-08',
    projectId: 'proj-c360-ingest',
    title: 'Lakehouse Ingestion Table Batch Completed',
    description: 'CRM Account Profiles bulk snapshot synced 14.8M rows to Snowflake staging.',
    category: 'MIGRATION',
    severity: 'SUCCESS',
    occurredAt: '2026-09-07T11:15:00Z',
    actorName: 'akaal-pipeline-worker-sa',
    actorType: 'SERVICE_ACCOUNT',
    subjectName: 'Customer 360 Lakehouse Ingestion',
    subjectType: 'MIGRATION',
    actionType: 'VIEW',
    availability: 'READY'
  }
];

export const FIXTURE_PROJECT_ACCESS_GRANTS: import('./projects.models').ProjectAccessGrantItem[] = [
  {
    id: 'grant-01',
    projectId: 'proj-core-banking',
    principalId: 'usr-aalok-ladwa',
    principalName: 'Aalok Ladwa',
    principalEmail: 'aalok.ladwa@enterprise.corp',
    principalType: 'USER',
    role: 'PROJECT_ADMIN',
    accessSource: 'DIRECT_PROJECT',
    scopeDescription: 'Explicit Project Administration Grant',
    grantedAt: '2026-02-01T08:00:00Z',
    status: 'ACTIVE',
    availability: 'READY'
  },
  {
    id: 'grant-02',
    projectId: 'proj-core-banking',
    principalId: 'grp-cloud-engineers',
    principalName: 'Cloud Migration Engineering Team',
    principalEmail: 'cloud-mig-eng@enterprise.corp',
    principalType: 'GROUP',
    role: 'OPERATOR',
    accessSource: 'DIRECT_PROJECT',
    scopeDescription: 'Direct Operator Assignment for Pipeline Execution',
    grantedAt: '2026-02-10T10:00:00Z',
    status: 'ACTIVE',
    availability: 'READY'
  },
  {
    id: 'grant-03',
    projectId: 'proj-core-banking',
    principalId: 'sa-pipeline-worker',
    principalName: 'akaal-pipeline-worker-sa',
    principalEmail: 'service-account-pipeline@sys.akaal.internal',
    principalType: 'SERVICE_ACCOUNT',
    role: 'OPERATOR',
    accessSource: 'DIRECT_PROJECT',
    scopeDescription: 'Automated Migration Daemon Principal',
    grantedAt: '2026-02-01T08:00:00Z',
    status: 'ACTIVE',
    availability: 'READY'
  },
  {
    id: 'grant-04',
    projectId: 'proj-core-banking',
    principalId: 'usr-sarah-jenkins',
    principalName: 'Sarah Jenkins (Lead DBA)',
    principalEmail: 's.jenkins@enterprise.corp',
    principalType: 'USER',
    role: 'PROJECT_ADMIN',
    accessSource: 'INHERITED_WORKSPACE',
    scopeDescription: 'Workspace Security Custodian (Inherited from ws-prod-emea)',
    grantedAt: '2026-01-15T09:00:00Z',
    status: 'ACTIVE',
    availability: 'READY'
  },
  {
    id: 'grant-05',
    projectId: 'proj-core-banking',
    principalId: 'grp-data-gov',
    principalName: 'Enterprise Data Governance Office',
    principalEmail: 'data-gov@enterprise.corp',
    principalType: 'GROUP',
    role: 'VIEWER',
    accessSource: 'INHERITED_WORKSPACE',
    scopeDescription: 'Audit and Parity Inspection Scope (Inherited from ws-prod-emea)',
    grantedAt: '2026-01-20T14:00:00Z',
    status: 'ACTIVE',
    availability: 'READY'
  },
  {
    id: 'grant-06',
    projectId: 'proj-payments-gw',
    principalId: 'usr-aalok-ladwa',
    principalName: 'Aalok Ladwa',
    principalEmail: 'aalok.ladwa@enterprise.corp',
    principalType: 'USER',
    role: 'PROJECT_ADMIN',
    accessSource: 'DIRECT_PROJECT',
    scopeDescription: 'Explicit Project Administration Grant',
    grantedAt: '2026-02-15T11:00:00Z',
    status: 'ACTIVE',
    availability: 'READY'
  },
  {
    id: 'grant-07',
    projectId: 'proj-payments-gw',
    principalId: 'grp-cloud-engineers',
    principalName: 'Cloud Migration Engineering Team',
    principalEmail: 'cloud-mig-eng@enterprise.corp',
    principalType: 'GROUP',
    role: 'OPERATOR',
    accessSource: 'DIRECT_PROJECT',
    scopeDescription: 'Settlement Stream Execution Role',
    grantedAt: '2026-02-16T12:00:00Z',
    status: 'ACTIVE',
    availability: 'READY'
  },
  {
    id: 'grant-08',
    projectId: 'proj-c360-ingest',
    principalId: 'usr-aalok-ladwa',
    principalName: 'Aalok Ladwa',
    principalEmail: 'aalok.ladwa@enterprise.corp',
    principalType: 'USER',
    role: 'PROJECT_ADMIN',
    accessSource: 'DIRECT_PROJECT',
    scopeDescription: 'Explicit Project Administration Grant',
    grantedAt: '2026-03-10T10:00:00Z',
    status: 'ACTIVE',
    availability: 'READY'
  }
];

export const FIXTURE_PROJECT_GOVERNANCE_ITEMS: import('./projects.models').ProjectGovernanceItem[] = [
  {
    id: 'gov-01',
    projectId: 'proj-core-banking',
    title: 'Stage 3 Dual-Run Cutover Gate Authorization',
    description: 'Mandatory four-eyes signoff required before transitioning accounts replication to active-active cutover window.',
    category: 'PENDING_APPROVAL',
    protectedOperation: 'MIGRATION_CUTOVER_GATE',
    status: 'PENDING',
    severity: 'CRITICAL',
    requestedAt: '2026-09-07T14:30:00Z',
    requestedBy: 'Aalok Ladwa',
    policyReference: 'POL-MIG-SEC-04: Mandatory Dual Signoff for Production Ledgers',
    actionLabel: 'Review Approval',
    actionRoute: '/migration/cockpit/mig-cb-01',
    availability: 'READY'
  },
  {
    id: 'gov-02',
    projectId: 'proj-core-banking',
    title: 'Mandatory Schema Parity Assertion',
    description: 'All relational tables must pass Val Mission structural verification with zero critical discrepancies prior to replication initiation.',
    category: 'POLICY_REQUIREMENT',
    protectedOperation: 'PRE_FLIGHT_VALIDATION',
    status: 'ACTIVE',
    severity: 'WARNING',
    requestedAt: '2026-02-01T08:00:00Z',
    policyReference: 'POL-VAL-01: Zero Discrepancy Gate for Financial ledgers',
    actionLabel: 'Inspect Policy',
    availability: 'READY'
  },
  {
    id: 'gov-03',
    projectId: 'proj-core-banking',
    title: 'Initial CDC Pipeline Provisioning Approval',
    description: 'Approved Oracle LogMiner CDC engine deployment on production database instance.',
    category: 'RESOLVED_DECISION',
    protectedOperation: 'DEPLOY_PIPELINE_AGENT',
    status: 'APPROVED',
    severity: 'INFO',
    requestedAt: '2026-02-05T10:00:00Z',
    requestedBy: 'Aalok Ladwa',
    resolvedAt: '2026-02-06T11:30:00Z',
    resolvedBy: 'Sarah Jenkins (Lead DBA)',
    policyReference: 'POL-OPS-03: Production DB Extension Protocol',
    actionLabel: 'View Resolution',
    availability: 'READY'
  },
  {
    id: 'gov-04',
    projectId: 'proj-core-banking',
    title: 'Temporary Secondary Index Lag Waiver',
    description: 'Permitted 15-minute lag tolerance for non-transactional reporting views during high-throughput historical bulk migration.',
    category: 'EXCEPTION_WAIVER',
    protectedOperation: 'REPLICATION_LAG_THRESHOLD',
    status: 'WAIVED',
    severity: 'INFO',
    requestedAt: '2026-03-01T09:00:00Z',
    requestedBy: 'Cloud Migration Engineering Team',
    resolvedAt: '2026-03-01T14:00:00Z',
    resolvedBy: 'Enterprise Data Governance Office',
    policyReference: 'WVR-2026-CB-09: Bulk Phase Latency Concession',
    actionLabel: 'Inspect Waiver',
    availability: 'READY'
  },
  {
    id: 'gov-05',
    projectId: 'proj-payments-gw',
    title: 'Kafka SASL_SSL Security Policy Compliance',
    description: 'All streaming consumers must establish mutually authenticated TLS sessions against corporate schema registry.',
    category: 'POLICY_REQUIREMENT',
    protectedOperation: 'STREAM_ENCRYPTION_GUARD',
    status: 'ACTIVE',
    severity: 'INFO',
    requestedAt: '2026-02-15T11:00:00Z',
    policyReference: 'POL-NET-08: Transport Encryption Standard',
    availability: 'READY'
  }
];



