"""
akaalEngine.schema.ddl.providers.db2
===================================
IBM Db2 target DDL emitter for Authority #4 Schema.
Handles Db2 uppercase identifier conventions, staged constraints, sequences, and tablespace clauses.
"""

from typing import List, Optional

from akaalEngine.schema.ddl.emitter import (
    BaseTargetDDLEmitter,
    DDLStage,
    StructuredDDLArtifact,
)
from akaalEngine.schema.ddl.identifiers import IdentifierSanitizer
from akaalEngine.schema.models.programmables import (
    CanonicalRoutine,
    CanonicalSequence,
    CanonicalTrigger,
    CanonicalUDT,
)
from akaalEngine.schema.models.schema import CanonicalView
from akaalEngine.schema.models.table import CanonicalTable
from akaalEngine.schema.models.types import ConversionSafety
from akaalEngine.schema.types.emitters import ProviderTypeEmitters


class Db2DDLEmitter(BaseTargetDDLEmitter):
    """DDL emitter for IBM Db2 targets."""

    def __init__(self, target_engine: str = "DB2"):
        super().__init__(target_engine="DB2")

    def emit_schema_artifacts(self, schema_name: str) -> List[StructuredDDLArtifact]:
        s_name = IdentifierSanitizer.sanitize_identifier(schema_name, "DB2")
        return [
            StructuredDDLArtifact(
                object_type="SCHEMA",
                object_name=schema_name,
                schema_name=schema_name,
                sql=f"CREATE SCHEMA {s_name}",
                target_engine="DB2",
                stage=DDLStage.SCHEMAS,
            )
        ]

    def emit_table_artifacts(self, table: CanonicalTable, source_engine: str = "GENERIC") -> List[StructuredDDLArtifact]:
        artifacts: List[StructuredDDLArtifact] = []
        tbl_qual = IdentifierSanitizer.format_qualified_name(table.schema_name, table.table_name, "DB2")

        col_defs = []
        for col in table.columns:
            c_name = IdentifierSanitizer.sanitize_identifier(col.name, "DB2")
            emission = ProviderTypeEmitters.emit_target_type(col.canonical_type, "DB2")
            col_sql = f"{c_name} {emission.target_native_type}"

            if not col.nullable:
                col_sql += " NOT NULL"
            if col.default_expression:
                col_sql += f" DEFAULT {col.default_expression}"
            if col.is_identity:
                col_sql += " GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)"
            col_defs.append(col_sql)

        body = ",\n  ".join(col_defs)
        create_table_sql = f"CREATE TABLE {tbl_qual} (\n  {body}\n)"

        artifacts.append(
            StructuredDDLArtifact(
                object_type="TABLE",
                object_name=table.table_name,
                schema_name=table.schema_name,
                sql=create_table_sql,
                target_engine="DB2",
                stage=DDLStage.TABLES,
            )
        )

        # Primary Key
        if table.primary_key and table.primary_key.columns:
            pk_name = IdentifierSanitizer.sanitize_identifier(table.primary_key.name or f"PK_{table.table_name}", "DB2")
            pk_cols = ", ".join(IdentifierSanitizer.sanitize_identifier(c, "DB2") for c in table.primary_key.columns)
            pk_sql = f"ALTER TABLE {tbl_qual} ADD CONSTRAINT {pk_name} PRIMARY KEY ({pk_cols})"
            artifacts.append(
                StructuredDDLArtifact(
                    object_type="PRIMARY_KEY",
                    object_name=table.primary_key.name or f"PK_{table.table_name}",
                    schema_name=table.schema_name,
                    sql=pk_sql,
                    target_engine="DB2",
                    stage=DDLStage.PRIMARY_KEYS,
                    dependencies=(table.qualified_name,),
                )
            )

        # Indexes
        for idx in table.indexes:
            idx_name = IdentifierSanitizer.sanitize_identifier(idx.name, "DB2")
            idx_cols = ", ".join(IdentifierSanitizer.sanitize_identifier(c, "DB2") for c in idx.columns)
            unique_kw = "UNIQUE " if idx.is_unique else ""
            idx_sql = f"CREATE {unique_kw}INDEX {idx_name} ON {tbl_qual} ({idx_cols})"
            artifacts.append(
                StructuredDDLArtifact(
                    object_type="INDEX",
                    object_name=idx.name,
                    schema_name=table.schema_name,
                    sql=idx_sql,
                    target_engine="DB2",
                    stage=DDLStage.INDEXES,
                    dependencies=(table.qualified_name,),
                )
            )

        # Foreign Keys
        for fk in table.foreign_keys:
            fk_name = IdentifierSanitizer.sanitize_identifier(fk.name or f"FK_{table.table_name}_{fk.referenced_table}", "DB2")
            fk_cols = ", ".join(IdentifierSanitizer.sanitize_identifier(c, "DB2") for c in fk.columns)
            ref_qual = IdentifierSanitizer.format_qualified_name(fk.referenced_schema, fk.referenced_table, "DB2")
            ref_cols = ", ".join(IdentifierSanitizer.sanitize_identifier(c, "DB2") for c in fk.referenced_columns)
            fk_sql = f"ALTER TABLE {tbl_qual} ADD CONSTRAINT {fk_name} FOREIGN KEY ({fk_cols}) REFERENCES {ref_qual} ({ref_cols})"
            if fk.on_delete != "NO ACTION":
                fk_sql += f" ON DELETE {fk.on_delete}"
            if fk.on_update != "NO ACTION":
                fk_sql += f" ON UPDATE {fk.on_update}"

            ref_full = f"{fk.referenced_schema}.{fk.referenced_table}" if fk.referenced_schema else fk.referenced_table
            artifacts.append(
                StructuredDDLArtifact(
                    object_type="FOREIGN_KEY",
                    object_name=fk.name or f"FK_{table.table_name}_{fk.referenced_table}",
                    schema_name=table.schema_name,
                    sql=fk_sql,
                    target_engine="DB2",
                    stage=DDLStage.FOREIGN_KEYS,
                    dependencies=(table.qualified_name, ref_full),
                )
            )

        return artifacts

    def emit_view_artifacts(self, view: CanonicalView, source_engine: str = "GENERIC") -> List[StructuredDDLArtifact]:
        v_qual = IdentifierSanitizer.format_qualified_name(view.schema_name, view.view_name, "DB2")
        query = view.view_definition or "SELECT 1 FROM SYSIBM.SYSDUMMY1"
        sql = f"CREATE VIEW {v_qual} AS\n{query}"
        return [
            StructuredDDLArtifact(
                object_type="VIEW",
                object_name=view.view_name,
                schema_name=view.schema_name,
                sql=sql,
                target_engine="DB2",
                stage=DDLStage.VIEWS,
            )
        ]

    def emit_sequence_artifacts(self, sequence: CanonicalSequence) -> List[StructuredDDLArtifact]:
        s_qual = IdentifierSanitizer.format_qualified_name(sequence.schema_name, sequence.name, "DB2")
        sql = f"CREATE SEQUENCE {s_qual} START WITH {sequence.start_value} INCREMENT BY {sequence.increment_by}"
        if sequence.min_value is not None:
            sql += f" MINVALUE {sequence.min_value}"
        if sequence.max_value is not None:
            sql += f" MAXVALUE {sequence.max_value}"
        if sequence.is_cycling:
            sql += " CYCLE"
        if sequence.cache_size > 1:
            sql += f" CACHE {sequence.cache_size}"
        return [
            StructuredDDLArtifact(
                object_type="SEQUENCE",
                object_name=sequence.name,
                schema_name=sequence.schema_name,
                sql=sql,
                target_engine="DB2",
                stage=DDLStage.SEQUENCES,
            )
        ]

    def emit_udt_artifacts(self, udt: CanonicalUDT) -> List[StructuredDDLArtifact]:
        u_qual = IdentifierSanitizer.format_qualified_name(udt.schema_name, udt.name, "DB2")
        if udt.underlying_type:
            sql = f"CREATE DISTINCT TYPE {u_qual} AS {udt.underlying_type} WITH WEAK TYPE RULES"
            return [
                StructuredDDLArtifact(
                    object_type="UDT",
                    object_name=udt.name,
                    schema_name=udt.schema_name,
                    sql=sql,
                    target_engine="DB2",
                    stage=DDLStage.TYPES,
                )
            ]
        return []
