[pytest]
testpaths = tests
norecursedirs = scripts tests/archive .venv
addopts = --import-mode=importlib --ignore=tests/integration/test_bed_cdc.py --ignore=tests/integration/test_bed_data.py --ignore=tests/integration/test_bed_setup.py
python_files = test_*.py
python_classes = Test* !TestSpecDataclass !TestingManager
python_functions = test_*
