"""SimulationEngine and SimulationReport for non-mutating preview simulation."""

import time
from typing import Dict, Any, List
from dataclasses import dataclass, field
from akaal.replication.sandbox.predictor import FailurePredictor


@dataclass
class SimulationReport:
    """Detailed report generated by replication dry-run simulation."""

    plan_id: str
    predicted_duration_ms: float
    predicted_lag_ms: float
    predicted_throughput_rows_sec: float
    rollback_probability: float
    estimated_recovery_time_sec: float
    is_safe: bool
    affected_nodes: List[str]
    timestamp: float = field(default_factory=time.time)


class SimulationEngine:
    """Simulates replication plan execution without modifying production data."""

    def __init__(self):
        self.predictor = FailurePredictor()

    def simulate(self, plan: Any) -> SimulationReport:
        pred = self.predictor.predict(plan)
        nodes = []
        for act in getattr(plan, "actions", []):
            if hasattr(act, "source_node_id") and act.source_node_id not in nodes:
                nodes.append(act.source_node_id)
            if hasattr(act, "target_node_id") and act.target_node_id not in nodes:
                nodes.append(act.target_node_id)

        return SimulationReport(
            plan_id=getattr(plan, "plan_id", "sim_plan_01"),
            predicted_duration_ms=pred["estimated_duration_ms"],
            predicted_lag_ms=pred["predicted_lag_ms"],
            predicted_throughput_rows_sec=pred["predicted_throughput_rows_sec"],
            rollback_probability=pred["rollback_probability"],
            estimated_recovery_time_sec=pred["estimated_recovery_time_sec"],
            is_safe=pred["is_safe"],
            affected_nodes=nodes,
        )
