"""
Akaal — Comparison Differences & Reports
=========================================
Defines the difference models, categories, severities, impact levels,
reproducible hashing identifier, and the final DifferenceReport model.
"""

import hashlib
from abc import ABC
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple
from akaal.core.models.enums import SystemType
from akaal.core.comparison.models.context import ComparisonContext
from akaal.core.comparison.models.schema import TableSchema, ColumnSchema, PrimaryKeySchema, ForeignKeySchema, IndexSchema, ConstraintSchema
from akaal.core.comparison.models.summary import ComparisonSummary


class SchemaComparisonStatus(str, Enum):
    IDENTICAL = "IDENTICAL"
    DIFFERENT = "DIFFERENT"


class DifferenceCategory(str, Enum):
    TABLE = "TABLE"
    COLUMN = "COLUMN"
    PRIMARY_KEY = "PRIMARY_KEY"
    FOREIGN_KEY = "FOREIGN_KEY"
    INDEX = "INDEX"
    CONSTRAINT = "CONSTRAINT"


class DifferenceAction(str, Enum):
    ADD = "ADD"
    REMOVE = "REMOVE"
    MODIFY = "MODIFY"


class DifferenceSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class MigrationImpact(str, Enum):
    NO_IMPACT = "NO_IMPACT"
    METADATA_ONLY = "METADATA_ONLY"
    ONLINE_DDL = "ONLINE_DDL"
    OFFLINE_DDL = "OFFLINE_DDL"
    DESTRUCTIVE = "DESTRUCTIVE"


def generate_deterministic_id(category: str, path: str, action: str, details: Optional[str] = None) -> str:
    """
    Generates a stable, reproducible SHA-256 hex hash matching the difference payload.
    Used for tracking and referencing differences deterministically.
    """
    payload = f"{category.upper()}:{path.lower()}:{action.upper()}"
    if details:
        payload += f":{details}"
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class SchemaDifference(ABC):
    """
    Polymorphic base representation of a structural schema difference.
    Includes rich metadata and severity/impact classifications for downstream AI planning.
    """
    difference_id: str
    category: DifferenceCategory
    action: DifferenceAction
    path: str
    severity: DifferenceSeverity
    impact: MigrationImpact
    description: str  # Strictly display-only text
    ai_metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class TableDifference(SchemaDifference):
    table_name: str = ""
    expected: Optional[TableSchema] = None
    actual: Optional[TableSchema] = None


@dataclass(frozen=True)
class ColumnDifference(SchemaDifference):
    table_name: str = ""
    column_name: str = ""
    expected: Optional[ColumnSchema] = None
    actual: Optional[ColumnSchema] = None
    type_mismatch: bool = False
    nullability_mismatch: bool = False
    default_mismatch: bool = False


@dataclass(frozen=True)
class PrimaryKeyDifference(SchemaDifference):
    table_name: str = ""
    expected: Optional[PrimaryKeySchema] = None
    actual: Optional[PrimaryKeySchema] = None


@dataclass(frozen=True)
class ForeignKeyDifference(SchemaDifference):
    table_name: str = ""
    fk_name: str = ""
    expected: Optional[ForeignKeySchema] = None
    actual: Optional[ForeignKeySchema] = None


@dataclass(frozen=True)
class IndexDifference(SchemaDifference):
    table_name: str = ""
    index_name: str = ""
    expected: Optional[IndexSchema] = None
    actual: Optional[IndexSchema] = None
    uniqueness_mismatch: bool = False


@dataclass(frozen=True)
class ConstraintDifference(SchemaDifference):
    table_name: str = ""
    constraint_name: str = ""
    expected: Optional[ConstraintSchema] = None
    actual: Optional[ConstraintSchema] = None


@dataclass(frozen=True)
class DifferenceReport:
    """
    Structured comparison report generated by the SchemaComparisonEngine.
    """
    report_id: str
    report_version: str
    comparison_timestamp: datetime
    source_vendor: SystemType
    target_vendor: SystemType
    engine_version: str
    comparison_options: ComparisonContext
    source_checksum: str
    target_checksum: str
    status: SchemaComparisonStatus
    differences: Tuple[SchemaDifference, ...]
    summary_statistics: ComparisonSummary
