"""
akaalEngine.discovery
=====================
Authority #3 Discovery — Master Physical Introspection, Crawling, Topology & Sizing Engine.
"""

from akaalEngine.discovery.authority import (
    DiscoveryAuthority,
    default_discovery_authority,
)
from akaalEngine.discovery.errors import (
    CorruptedCatalogDiscoveryError,
    DiscoveryEngineException,
    DiscoveryTimeoutError,
    EndpointUnreachableDiscoveryError,
    ObjectDisappearedDiscoveryError,
    PermissionDeniedDiscoveryError,
    SchemaMutationDuringScanError,
    UnsupportedDiscoveryFeatureError,
)
from akaalEngine.discovery.models import (
    CDCMechanism,
    CDCPrerequisiteSnapshot,
    CharsetFacts,
    CheckConstraintFacts,
    ClusterNodeFacts,
    CollationFacts,
    ColumnCardinalityFacts,
    ColumnPhysicalMetadata,
    ConfigurationFacts,
    ConstraintType,
    CountAccuracy,
    DiscoveredEndpointIdentity,
    DiscoveryCompleteness,
    DiscoveryContext,
    DiscoveryDepth,
    DiscoveryFingerprint,
    DiscoveryScope,
    DiscoverySnapshot,
    EngineEdition,
    ForeignKeyFacts,
    IndexAccessMethod,
    IndexFacts,
    InferredDocumentShape,
    LargestObjectItem,
    LimitsFacts,
    LOBVolumeFacts,
    NamespaceInventory,
    NodeRole,
    ObjectClassification,
    ObjectInventory,
    ObjectInventoryPage,
    ObjectStructureFacts,
    ObjectType,
    PartitionBoundFacts,
    PartitionFacts,
    PartitionStrategy,
    PermissionAssessment,
    PrimaryKeyFacts,
    PrivilegeFact,
    ProgrammableInventory,
    RoutineFacts,
    RoutineParameterFacts,
    RoutineType,
    SampledFieldObservation,
    SampledRecordSet,
    SequenceFacts,
    ServerVersion,
    StartingCommitPosition,
    StatisticsSnapshot,
    SubpartitionFacts,
    TableFacts,
    TableSizeFacts,
    ThreeStatePermission,
    TimezoneFacts,
    TokenRangeFacts,
    TopologySnapshot,
    TriggerFacts,
    TriggerTiming,
    UDTFacts,
    UniqueConstraintFacts,
    ViewFacts,
    VolumeSnapshot,
)
from akaalEngine.discovery.spi import (
    BaseDiscoveryStrategy,
    NoSQLDiscoveryStrategy,
    RelationalDiscoveryStrategy,
    StorageDiscoveryStrategy,
    StreamingDiscoveryStrategy,
    WarehouseDiscoveryStrategy,
)

__all__ = [
    # Facade
    "DiscoveryAuthority",
    "default_discovery_authority",
    # Context
    "DiscoveryDepth",
    "DiscoveryScope",
    "DiscoveryContext",
    # Snapshot & Fingerprint
    "DiscoveryCompleteness",
    "DiscoveryFingerprint",
    "DiscoverySnapshot",
    # Identity
    "ServerVersion",
    "EngineEdition",
    "DiscoveredEndpointIdentity",
    # Inventory
    "ObjectClassification",
    "ObjectType",
    "TableFacts",
    "ViewFacts",
    "NamespaceInventory",
    "ObjectInventory",
    "ObjectInventoryPage",
    # Structure
    "ConstraintType",
    "IndexAccessMethod",
    "ColumnPhysicalMetadata",
    "PrimaryKeyFacts",
    "ForeignKeyFacts",
    "UniqueConstraintFacts",
    "CheckConstraintFacts",
    "IndexFacts",
    "ObjectStructureFacts",
    # Programmables
    "RoutineType",
    "TriggerTiming",
    "RoutineParameterFacts",
    "RoutineFacts",
    "TriggerFacts",
    "SequenceFacts",
    "UDTFacts",
    "ProgrammableInventory",
    # Partitioning
    "PartitionStrategy",
    "PartitionBoundFacts",
    "SubpartitionFacts",
    "TokenRangeFacts",
    "PartitionFacts",
    # Statistics & Volume
    "CountAccuracy",
    "TableSizeFacts",
    "ColumnCardinalityFacts",
    "StatisticsSnapshot",
    "LargestObjectItem",
    "LOBVolumeFacts",
    "VolumeSnapshot",
    # Permissions
    "ThreeStatePermission",
    "PrivilegeFact",
    "PermissionAssessment",
    # Topology
    "NodeRole",
    "ClusterNodeFacts",
    "TopologySnapshot",
    # CDC
    "CDCMechanism",
    "StartingCommitPosition",
    "CDCPrerequisiteSnapshot",
    # Environment
    "CharsetFacts",
    "CollationFacts",
    "TimezoneFacts",
    "LimitsFacts",
    "ConfigurationFacts",
    # Sampling
    "SampledFieldObservation",
    "InferredDocumentShape",
    "SampledRecordSet",
    # SPI
    "BaseDiscoveryStrategy",
    "RelationalDiscoveryStrategy",
    "WarehouseDiscoveryStrategy",
    "NoSQLDiscoveryStrategy",
    "StreamingDiscoveryStrategy",
    "StorageDiscoveryStrategy",
    # Exceptions
    "DiscoveryEngineException",
    "PermissionDeniedDiscoveryError",
    "EndpointUnreachableDiscoveryError",
    "ObjectDisappearedDiscoveryError",
    "DiscoveryTimeoutError",
    "CorruptedCatalogDiscoveryError",
    "UnsupportedDiscoveryFeatureError",
    "SchemaMutationDuringScanError",
]
