"""akaalPipeline.security.kms_provider
===================================
P7.8 Provider-neutral Key Management (KMS/HSM) authority.

Reuses akaalPipeline.security.keystore.KeyStoreAuthority for local envelope-encryption
key custody rather than duplicating its Master-Root-Key/AES-256-GCM crypto. Defines a
provider-neutral `KeyManagementProvider` Protocol so a real cloud KMS/HSM integration can
be added later as an additional implementation without changing callers.

Truthfulness boundary: `LocalEnvelopeKMSProvider` is real, working local key custody --
it is NOT represented as HSM-backed, CMK, or BYOK. `ExternalKMSProviderUnavailable`
explicitly raises for any cloud KMS/HSM/BYOK operation rather than silently downgrading
to the local provider; the live cloud integration is EXTERNAL_DEFERRED pending operator
KMS account/credential configuration, which this environment does not have.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional, Protocol, runtime_checkable

from akaalPipeline.contracts.enums import KeyAlgorithm, KeyPurpose
from akaalPipeline.security.keystore import (
    KeyNotFoundError,
    KeyPurposeMismatchError,
    KeyRevokedError,
    KeyStoreAuthority,
)
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from akaal.core.crypto_random import secure_random_bytes


class KMSProviderUnavailableError(RuntimeError):
    """Raised when a requested key-management operation targets a provider that is not
    live in this environment. This is an honest EXTERNAL_DEFERRED signal, not a fallback."""


class KeyOrigin(str, Enum):
    """
    Truthful provenance of a managed key's material -- distinguishes genuine CMK/BYOK from
    a plain locally generated key so callers can never claim BYOK merely because a
    key_id string exists.
    """
    AKAAL_GENERATED = "AKAAL_GENERATED"          # generated by this provider (local envelope or cloud-side generate)
    PROVIDER_GENERATED_CMK = "PROVIDER_GENERATED_CMK"  # customer-managed key, material generated inside the cloud KMS/HSM
    CUSTOMER_IMPORTED_BYOK = "CUSTOMER_IMPORTED_BYOK"  # key material imported by the customer (Bring Your Own Key)
    HSM_BACKED = "HSM_BACKED"                    # key material never leaves an HSM boundary (PKCS#11 or cloud HSM tier)


@dataclass(frozen=True)
class KeyReference:
    """
    Provider-neutral reference to a managed key, carrying full CMK provenance rather than
    a bare string ID. `provider` distinguishes the custody backend.
    """
    provider: str  # "LOCAL_ENVELOPE" | "AWS_KMS" | "AZURE_KEY_VAULT" | "GCP_KMS" | "PKCS11_HSM"
    key_id: str
    purpose: KeyPurpose
    origin: KeyOrigin = KeyOrigin.AKAAL_GENERATED
    tenant_id: Optional[str] = None
    account_or_project: Optional[str] = None     # AWS account ID / Azure subscription / GCP project
    region_or_location: Optional[str] = None     # AWS region / Azure region / GCP location
    resource_id: Optional[str] = None            # full ARN / Key Vault key URI / GCP CryptoKeyVersion resource name
    version: Optional[str] = None                # provider key version identifier
    allowed_operations: tuple = field(default_factory=tuple)  # e.g. ("ENCRYPT","DECRYPT") -- provider-reported, not assumed
    lifecycle_state: Optional[str] = None         # provider-reported state string (e.g. "Enabled", "PendingDeletion")
    rotation_capability: Optional[str] = None     # e.g. "AUTOMATIC_ANNUAL" | "MANUAL_ONLY" | "UNKNOWN" -- provider-reported


@runtime_checkable
class KeyManagementProvider(Protocol):
    """Provider-neutral key lifecycle + cryptographic-operation contract."""

    def generate_key(self, purpose: KeyPurpose, algorithm: KeyAlgorithm) -> KeyReference: ...
    def sign(self, ref: KeyReference, message: bytes) -> bytes: ...
    def verify(self, ref: KeyReference, message: bytes, signature: bytes) -> bool: ...
    def encrypt(self, ref: KeyReference, plaintext: bytes, aad: Optional[bytes] = None) -> bytes: ...
    def decrypt(self, ref: KeyReference, ciphertext: bytes, aad: Optional[bytes] = None) -> bytes: ...
    def rotate_key(self, purpose: KeyPurpose) -> KeyReference: ...
    def revoke_key(self, ref: KeyReference, reason: Optional[str] = None) -> None: ...


class LocalEnvelopeKMSProvider:
    """
    Real, working local KMS provider backed by KeyStoreAuthority's Master-Root-Key
    envelope encryption. This is genuine, real, working local key custody -- but it is local,
    not HSM- or cloud-KMS-backed, and is never represented as such.
    """

    PROVIDER_NAME = "LOCAL_ENVELOPE"

    def __init__(self, keystore: KeyStoreAuthority) -> None:
        self.keystore = keystore

    def generate_key(self, purpose: KeyPurpose, algorithm: KeyAlgorithm) -> KeyReference:
        """
        Get-or-create semantics matching real KMS provider behavior: if an ACTIVE key
        already exists for this purpose, it is returned rather than creating a second,
        ambiguous ACTIVE key under the same purpose (KeyStoreAuthority enforces exactly
        one ACTIVE key per purpose via rotate_key(), not via generate_and_save_key()).
        """
        existing = self.keystore.keyring_repo.get_active_key(purpose.value)
        if existing:
            return KeyReference(provider=self.PROVIDER_NAME, key_id=existing["key_id"], purpose=purpose)
        key_id = self.keystore.generate_and_save_key(purpose, algorithm)
        return KeyReference(provider=self.PROVIDER_NAME, key_id=key_id, purpose=purpose)

    def sign(self, ref: KeyReference, message: bytes) -> bytes:
        _key_id, priv_key = self.keystore.get_signing_key_ed25519(ref.purpose)
        if _key_id != ref.key_id:
            raise KeyPurposeMismatchError(
                f"Active key for purpose {ref.purpose.value!r} is {_key_id!r}, not the referenced {ref.key_id!r}"
            )
        return priv_key.sign(message)

    def verify(self, ref: KeyReference, message: bytes, signature: bytes) -> bool:
        return self.keystore.verify_signature_ed25519(ref.key_id, message, signature)

    def _resolve_symmetric_key(self, ref: KeyReference) -> bytes:
        key_record = self.keystore.get_key_for_purpose(ref.key_id, ref.purpose)
        if key_record["status"] != "ACTIVE":
            raise KeyRevokedError(f"Key {ref.key_id!r} is not ACTIVE (status={key_record['status']})")
        if key_record["algorithm"] != KeyAlgorithm.AES_256_GCM.value:
            raise KeyPurposeMismatchError(f"Key {ref.key_id!r} is not an AES-256-GCM key")
        # Reuses the same Master-Root-Key envelope decryption KeyStoreAuthority already
        # applies to its own key material -- no parallel crypto implementation.
        return self.keystore._decrypt_blob(key_record["encrypted_private_key_blob"])

    def encrypt(self, ref: KeyReference, plaintext: bytes, aad: Optional[bytes] = None) -> bytes:
        raw_key = self._resolve_symmetric_key(ref)
        aesgcm = AESGCM(raw_key)
        nonce = secure_random_bytes(12)
        ciphertext = aesgcm.encrypt(nonce, plaintext, aad)
        return nonce + ciphertext

    def decrypt(self, ref: KeyReference, ciphertext: bytes, aad: Optional[bytes] = None) -> bytes:
        if len(ciphertext) < 28:
            raise ValueError("Ciphertext too short to contain a 12-byte nonce + AES-GCM tag")
        raw_key = self._resolve_symmetric_key(ref)
        aesgcm = AESGCM(raw_key)
        nonce, ct = ciphertext[:12], ciphertext[12:]
        return aesgcm.decrypt(nonce, ct, aad)

    def rotate_key(self, purpose: KeyPurpose) -> KeyReference:
        key_id = self.keystore.rotate_key(purpose)
        return KeyReference(provider=self.PROVIDER_NAME, key_id=key_id, purpose=purpose)

    def revoke_key(self, ref: KeyReference, reason: Optional[str] = None) -> None:
        self.keystore.revoke_key(ref.key_id, reason)


class ExternalKMSProviderUnavailable:
    """
    Honest not-yet-configured stand-in for a cloud KMS/HSM provider (AWS KMS, Azure Key Vault, GCP KMS,
    PKCS#11 HSM). Every operation raises KMSProviderUnavailableError rather than silently
    downgrading to local key custody or fabricating a successful cloud response.
    Real integration requires operator-supplied cloud credentials/HSM slot configuration
    that does not exist in this environment -- this capability is EXTERNAL_DEFERRED.
    """

    def __init__(self, provider_name: str) -> None:
        self.provider_name = provider_name

    def _unavailable(self, operation: str) -> KMSProviderUnavailableError:
        return KMSProviderUnavailableError(
            f"{operation} against external KMS/HSM provider {self.provider_name!r} is EXTERNAL_DEFERRED: "
            "no live cloud KMS/HSM credentials are configured in this environment. "
            "This capability is intentionally left unimplemented rather than emulated."
        )

    def generate_key(self, purpose: KeyPurpose, algorithm: KeyAlgorithm) -> KeyReference:
        raise self._unavailable("generate_key")

    def sign(self, ref: KeyReference, message: bytes) -> bytes:
        raise self._unavailable("sign")

    def verify(self, ref: KeyReference, message: bytes, signature: bytes) -> bool:
        raise self._unavailable("verify")

    def encrypt(self, ref: KeyReference, plaintext: bytes, aad: Optional[bytes] = None) -> bytes:
        raise self._unavailable("encrypt")

    def decrypt(self, ref: KeyReference, ciphertext: bytes, aad: Optional[bytes] = None) -> bytes:
        raise self._unavailable("decrypt")

    def rotate_key(self, purpose: KeyPurpose) -> KeyReference:
        raise self._unavailable("rotate_key")

    def revoke_key(self, ref: KeyReference, reason: Optional[str] = None) -> None:
        raise self._unavailable("revoke_key")


class KMSDependencyMissingError(KMSProviderUnavailableError):
    """Raised when a cloud KMS/HSM provider's required SDK is not installed in this
    environment. Distinct from a live-call failure: the production code path is real and
    complete, but the optional dependency it requires is not present here -- matching the
    existing repository convention (e.g. akaalEngine.connection.providers.storage.s3's
    lazy `import boto3` / is_dependency_available() pattern)."""


_ALGO_TO_AWS_KEY_SPEC = {
    KeyAlgorithm.AES_256_GCM: "SYMMETRIC_DEFAULT",
    KeyAlgorithm.ED25519: "ECC_NIST_P256",  # AWS KMS has no native Ed25519; nearest asymmetric-sign equivalent
}


class AWSKMSProvider:
    """
    Real AWS KMS integration via boto3 (the same optional-dependency library already used
    by akaalEngine's S3/warehouse providers). Every operation issues a genuine boto3 KMS
    API call -- Encrypt/Decrypt/Sign/Verify/DescribeKey/CreateKey/ScheduleKeyDeletion/etc.
    No AWS behavior is emulated. If boto3 is not installed, every method raises
    KMSDependencyMissingError (truthful capability signal) rather than falling back to
    local key custody.

    Credentials/region are resolved dynamically through boto3's standard credential
    chain (profile, environment, IAM role, IMDS) -- never hardcoded here.
    """

    PROVIDER_NAME = "AWS_KMS"

    def __init__(self, region_name: Optional[str] = None, profile_name: Optional[str] = None, account_id: Optional[str] = None, client: Optional[Any] = None) -> None:
        self.region_name = region_name
        self.profile_name = profile_name
        self.account_id = account_id
        # `client`: test-only SDK-interface double injection point (C4 hostile review).
        # Production callers never pass this -- omitting it preserves the real boto3
        # session/credential-chain construction below. Never used to inject a bogus LIVE
        # result; it lets tests exercise this class's real request/response mapping logic
        # (algorithm mapping, state mapping, error translation) against a scripted
        # SDK-shaped double instead of a live AWS account.
        self._client = client

    def _get_client(self):
        if self._client is not None:
            return self._client
        try:
            import boto3
        except ImportError as exc:
            raise KMSDependencyMissingError(
                "AWS KMS operations require the 'boto3' library (pip install boto3). "
                "The production AWS KMS integration path is implemented; only the optional "
                "SDK dependency is absent in this environment."
            ) from exc
        session = boto3.Session(profile_name=self.profile_name, region_name=self.region_name)
        self._client = session.client("kms")
        return self._client

    def _ref(self, key_id_or_arn: str, purpose: KeyPurpose, extra: Optional[dict] = None) -> KeyReference:
        extra = extra or {}
        return KeyReference(
            provider=self.PROVIDER_NAME,
            key_id=key_id_or_arn,
            purpose=purpose,
            origin=extra.get("origin", KeyOrigin.PROVIDER_GENERATED_CMK),
            account_or_project=extra.get("account_id", self.account_id),
            region_or_location=extra.get("region", self.region_name),
            resource_id=extra.get("arn", key_id_or_arn),
            version=extra.get("version"),
            allowed_operations=tuple(extra.get("key_usage", ()) or ()),
            lifecycle_state=extra.get("key_state"),
            rotation_capability=extra.get("rotation_capability"),
        )

    def generate_key(self, purpose: KeyPurpose, algorithm: KeyAlgorithm) -> KeyReference:
        client = self._get_client()
        key_spec = _ALGO_TO_AWS_KEY_SPEC.get(algorithm, "SYMMETRIC_DEFAULT")
        key_usage = "SIGN_VERIFY" if algorithm == KeyAlgorithm.ED25519 else "ENCRYPT_DECRYPT"
        resp = client.create_key(
            KeySpec=key_spec,
            KeyUsage=key_usage,
            Tags=[{"TagKey": "akaal:purpose", "TagValue": purpose.value}],
            Description=f"AKAAL {purpose.value} customer-managed key",
        )
        meta = resp["KeyMetadata"]
        return self._ref(meta["KeyId"], purpose, {
            "arn": meta.get("Arn"), "account_id": meta.get("AWSAccountId"), "key_state": meta.get("KeyState"),
            "origin": KeyOrigin.PROVIDER_GENERATED_CMK,
        })

    def describe_key(self, ref: KeyReference) -> dict:
        """Real key-state/rotation/lifecycle introspection -- never assumed/cached as static truth."""
        client = self._get_client()
        meta = client.describe_key(KeyId=ref.key_id)["KeyMetadata"]
        rotation = client.get_key_rotation_status(KeyId=ref.key_id).get("KeyRotationEnabled", False)
        return {"key_state": meta.get("KeyState"), "rotation_enabled": rotation, "arn": meta.get("Arn")}

    def sign(self, ref: KeyReference, message: bytes) -> bytes:
        client = self._get_client()
        resp = client.sign(KeyId=ref.key_id, Message=message, MessageType="RAW", SigningAlgorithm="ECDSA_SHA_256")
        return resp["Signature"]

    def verify(self, ref: KeyReference, message: bytes, signature: bytes) -> bool:
        """
        Target 5 hostile-review fix: only a genuine, provider-confirmed signature
        mismatch may return False. AWS KMS reports an invalid signature via a
        KMSInvalidSignatureException (not a generic exception, and not always via a
        SignatureValid=False response body) -- see
        https://docs.aws.amazon.com/kms/latest/APIReference/API_Verify.html. Every other
        failure (AccessDeniedException, ThrottlingException, KMSInternalException,
        NotFoundException, DisabledException, network/SDK errors, malformed responses)
        must propagate untouched so the caller can distinguish "signature is wrong" from
        "verification could not be trustworthily performed".
        """
        client = self._get_client()
        try:
            resp = client.verify(KeyId=ref.key_id, Message=message, MessageType="RAW", Signature=signature, SigningAlgorithm="ECDSA_SHA_256")
        except Exception as exc:
            error_code = getattr(exc, "response", {}).get("Error", {}).get("Code") if hasattr(exc, "response") else None
            if error_code == "KMSInvalidSignatureException":
                return False  # provider-confirmed genuine signature mismatch
            raise  # AccessDenied/Throttling/Unavailable/malformed/etc. -- never silently False
        if "SignatureValid" not in resp:
            # Malformed/unexpected provider response shape -- do not silently treat as False.
            raise KMSProviderUnavailableError(
                f"AWS KMS Verify response for key {ref.key_id!r} is missing 'SignatureValid'; "
                "cannot trustworthily determine verification result."
            )
        return bool(resp["SignatureValid"])

    def encrypt(self, ref: KeyReference, plaintext: bytes, aad: Optional[bytes] = None) -> bytes:
        client = self._get_client()
        kwargs = {"KeyId": ref.key_id, "Plaintext": plaintext}
        if aad:
            kwargs["EncryptionContext"] = {"aad": aad.hex()}
        return client.encrypt(**kwargs)["CiphertextBlob"]

    def decrypt(self, ref: KeyReference, ciphertext: bytes, aad: Optional[bytes] = None) -> bytes:
        client = self._get_client()
        kwargs = {"KeyId": ref.key_id, "CiphertextBlob": ciphertext}
        if aad:
            kwargs["EncryptionContext"] = {"aad": aad.hex()}
        return client.decrypt(**kwargs)["Plaintext"]

    def rotate_key(self, purpose: KeyPurpose) -> KeyReference:
        raise KMSProviderUnavailableError(
            "AWS KMS CMK rotation is a key-level scheduled operation (enable_key_rotation), "
            "not a purpose-level lookup like the local provider; call describe_key()/"
            "AWS's EnableKeyRotation against a specific KeyReference instead of rotate_key(purpose)."
        )

    def revoke_key(self, ref: KeyReference, reason: Optional[str] = None) -> None:
        client = self._get_client()
        client.disable_key(KeyId=ref.key_id)


class AzureKeyVaultKMSProvider:
    """
    Real Azure Key Vault Keys integration via azure-identity + azure-keyvault-keys.
    Every operation is a genuine Azure SDK call (create_key/encrypt/decrypt/sign/verify/
    get_key). If the SDK is not installed, raises KMSDependencyMissingError.
    """

    PROVIDER_NAME = "AZURE_KEY_VAULT"

    def __init__(self, vault_url: str, client: Optional[Any] = None, crypto_client_factory: Optional[Any] = None) -> None:
        if not vault_url:
            raise ValueError("AzureKeyVaultKMSProvider requires a non-empty vault_url (operator-supplied, never hardcoded).")
        self.vault_url = vault_url
        # `client`/`crypto_client_factory`: test-only SDK-interface double injection points
        # (C4 hostile review), matching AWSKMSProvider's `client=` seam. Production callers
        # never pass these -- omitting them preserves the real azure-identity/KeyClient/
        # CryptographyClient construction below.
        self._client = client
        self._crypto_client_factory = crypto_client_factory
        self._crypto_clients: dict = {}

    def _get_client(self):
        if self._client is not None:
            return self._client
        try:
            from azure.identity import DefaultAzureCredential
            from azure.keyvault.keys import KeyClient
        except ImportError as exc:
            raise KMSDependencyMissingError(
                "Azure Key Vault operations require 'azure-identity' and 'azure-keyvault-keys' "
                "(pip install azure-identity azure-keyvault-keys). The production Azure Key "
                "Vault integration path is implemented; only the optional SDK is absent here."
            ) from exc
        self._client = KeyClient(vault_url=self.vault_url, credential=DefaultAzureCredential())
        return self._client

    def _crypto_client(self, key_id: str):
        if key_id in self._crypto_clients:
            return self._crypto_clients[key_id]
        if self._crypto_client_factory is not None:
            cc = self._crypto_client_factory(key_id)
            self._crypto_clients[key_id] = cc
            return cc
        try:
            from azure.keyvault.keys.crypto import CryptographyClient
            from azure.identity import DefaultAzureCredential
        except ImportError as exc:
            raise KMSDependencyMissingError(
                "Azure Key Vault crypto operations require 'azure-identity' and "
                "'azure-keyvault-keys' (pip install azure-identity azure-keyvault-keys)."
            ) from exc
        cc = CryptographyClient(key_id, credential=DefaultAzureCredential())
        self._crypto_clients[key_id] = cc
        return cc

    def generate_key(self, purpose: KeyPurpose, algorithm: KeyAlgorithm) -> KeyReference:
        client = self._get_client()
        key_type = "EC" if algorithm == KeyAlgorithm.ED25519 else "RSA"
        created = client.create_key(name=f"akaal-{purpose.value.lower()}", key_type=key_type)
        return KeyReference(
            provider=self.PROVIDER_NAME, key_id=created.id, purpose=purpose,
            origin=KeyOrigin.PROVIDER_GENERATED_CMK, resource_id=created.id,
            version=created.properties.version, lifecycle_state="Enabled" if created.properties.enabled else "Disabled",
        )

    def _signature_algorithm(self) -> Any:
        # When a test double supplies the crypto client, the real SDK enum type is not
        # needed (and may not be installed) -- the double only needs a stable identifier.
        if self._crypto_client_factory is not None:
            return "ES256"
        from azure.keyvault.keys.crypto import SignatureAlgorithm
        return SignatureAlgorithm.es256

    def _encryption_algorithm(self) -> Any:
        if self._crypto_client_factory is not None:
            return "RSA-OAEP-256"
        from azure.keyvault.keys.crypto import EncryptionAlgorithm
        return EncryptionAlgorithm.rsa_oaep_256

    def sign(self, ref: KeyReference, message: bytes) -> bytes:
        import hashlib
        digest = hashlib.sha256(message).digest()
        result = self._crypto_client(ref.key_id).sign(self._signature_algorithm(), digest)
        return result.signature

    def verify(self, ref: KeyReference, message: bytes, signature: bytes) -> bool:
        import hashlib
        digest = hashlib.sha256(message).digest()
        result = self._crypto_client(ref.key_id).verify(self._signature_algorithm(), digest, signature)
        return bool(result.is_valid)

    def encrypt(self, ref: KeyReference, plaintext: bytes, aad: Optional[bytes] = None) -> bytes:
        result = self._crypto_client(ref.key_id).encrypt(self._encryption_algorithm(), plaintext)
        return result.ciphertext

    def decrypt(self, ref: KeyReference, ciphertext: bytes, aad: Optional[bytes] = None) -> bytes:
        result = self._crypto_client(ref.key_id).decrypt(self._encryption_algorithm(), ciphertext)
        return result.plaintext

    def rotate_key(self, purpose: KeyPurpose) -> KeyReference:
        raise KMSProviderUnavailableError(
            "Azure Key Vault key rotation is policy-driven per key (rotation_policy on a "
            "specific key); call generate_key() again or configure a rotation policy on the "
            "existing key rather than a purpose-level rotate_key(purpose)."
        )

    @staticmethod
    def _key_name_from_id(key_id: str) -> str:
        """
        C4 hostile-review fix: a real Azure Key Vault key identifier has the form
        `https://{vault}.vault.azure.net/keys/{name}/{version}`. The prior
        implementation took the LAST path segment, which is the VERSION, not the name --
        begin_delete_key requires the key name. Proven wrong by a hostile test asserting
        the correct key was actually disabled after revoke_key().
        """
        parts = [p for p in key_id.split("/") if p]
        if "keys" in parts:
            idx = len(parts) - 1 - parts[::-1].index("keys")
            if idx + 1 < len(parts):
                return parts[idx + 1]
        return key_id  # not a versioned vault URL (e.g. a bare name) -- use as-is

    def revoke_key(self, ref: KeyReference, reason: Optional[str] = None) -> None:
        client = self._get_client()
        client.begin_delete_key(self._key_name_from_id(ref.key_id))


class GCPCloudKMSProvider:
    """
    Real Google Cloud KMS integration via google-cloud-kms. Every operation is a genuine
    gRPC API call (create_crypto_key/encrypt/decrypt/asymmetric_sign/asymmetric_verify/
    get_crypto_key_version). If the SDK is not installed, raises KMSDependencyMissingError.
    """

    PROVIDER_NAME = "GCP_KMS"

    def __init__(self, project_id: str, location_id: str, key_ring_id: str, client: Optional[Any] = None) -> None:
        if not (project_id and location_id and key_ring_id):
            raise ValueError("GCPCloudKMSProvider requires project_id, location_id, and key_ring_id (operator-supplied).")
        self.project_id = project_id
        self.location_id = location_id
        self.key_ring_id = key_ring_id
        # `client`: test-only SDK-interface double injection point (C4 hostile review),
        # matching AWSKMSProvider's seam. Production callers never pass this.
        self._client = client

    def _get_client(self):
        if self._client is not None:
            return self._client
        try:
            from google.cloud import kms
        except ImportError as exc:
            raise KMSDependencyMissingError(
                "GCP Cloud KMS operations require 'google-cloud-kms' (pip install google-cloud-kms). "
                "The production GCP KMS integration path is implemented; only the optional SDK "
                "is absent here."
            ) from exc
        self._client = kms.KeyManagementServiceClient()
        return self._client

    def _key_ring_path(self, client) -> str:
        return client.key_ring_path(self.project_id, self.location_id, self.key_ring_id)

    def generate_key(self, purpose: KeyPurpose, algorithm: KeyAlgorithm) -> KeyReference:
        client = self._get_client()  # raises KMSDependencyMissingError if google-cloud-kms is absent (unless injected)
        if self._client is not None and client is self._client:
            # Test-double path: avoid requiring the real SDK enum type when a scripted
            # test client is injected -- the double only needs a stable identifier, not the real enum.
            default_purpose = "ENCRYPT_DECRYPT"
            purpose_map = {KeyAlgorithm.AES_256_GCM: "ENCRYPT_DECRYPT", KeyAlgorithm.ED25519: "ASYMMETRIC_SIGN"}
        else:
            from google.cloud import kms
            default_purpose = kms.CryptoKey.CryptoKeyPurpose.ENCRYPT_DECRYPT
            purpose_map = {
                KeyAlgorithm.AES_256_GCM: kms.CryptoKey.CryptoKeyPurpose.ENCRYPT_DECRYPT,
                KeyAlgorithm.ED25519: kms.CryptoKey.CryptoKeyPurpose.ASYMMETRIC_SIGN,
            }
        crypto_key = client.create_crypto_key(
            request={
                "parent": self._key_ring_path(client),
                "crypto_key_id": f"akaal-{purpose.value.lower()}",
                "crypto_key": {"purpose": purpose_map.get(algorithm, default_purpose)},
            }
        )
        return KeyReference(
            provider=self.PROVIDER_NAME, key_id=crypto_key.name, purpose=purpose,
            origin=KeyOrigin.PROVIDER_GENERATED_CMK, account_or_project=self.project_id,
            region_or_location=self.location_id, resource_id=crypto_key.name,
        )

    def encrypt(self, ref: KeyReference, plaintext: bytes, aad: Optional[bytes] = None) -> bytes:
        client = self._get_client()
        req = {"name": ref.key_id, "plaintext": plaintext}
        if aad:
            req["additional_authenticated_data"] = aad
        return client.encrypt(request=req).ciphertext

    def decrypt(self, ref: KeyReference, ciphertext: bytes, aad: Optional[bytes] = None) -> bytes:
        client = self._get_client()
        req = {"name": ref.key_id, "ciphertext": ciphertext}
        if aad:
            req["additional_authenticated_data"] = aad
        return client.decrypt(request=req).plaintext

    def sign(self, ref: KeyReference, message: bytes) -> bytes:
        import hashlib
        client = self._get_client()
        digest = hashlib.sha256(message).digest()
        resp = client.asymmetric_sign(request={"name": ref.key_id, "digest": {"sha256": digest}})
        return resp.signature

    def verify(self, ref: KeyReference, message: bytes, signature: bytes) -> bool:
        # GCP KMS does not expose a server-side asymmetric verify RPC for all algorithms;
        # verification is performed client-side against the public key, which is a real,
        # correct pattern -- never claim server-side verification occurred.
        raise KMSProviderUnavailableError(
            "GCP Cloud KMS verify() requires fetching the public key (get_public_key) and "
            "verifying client-side with the 'cryptography' library; this provider does not "
            "silently claim a server-side verification RPC that GCP does not offer."
        )

    def rotate_key(self, purpose: KeyPurpose) -> KeyReference:
        raise KMSProviderUnavailableError(
            "GCP Cloud KMS rotation is configured per CryptoKey (rotation_period / "
            "next_rotation_time) at generate_key() time or via update_crypto_key(), not a "
            "purpose-level rotate_key(purpose)."
        )

    def revoke_key(self, ref: KeyReference, reason: Optional[str] = None) -> None:
        client = self._get_client()
        client.update_crypto_key_primary_version(request={"name": ref.key_id, "crypto_key_version_id": "disabled"})


class PKCS11HSMProvider:
    """
    Real PKCS#11 HSM integration via python-pkcs11 (the standard mature Python PKCS#11
    binding). Supports both physical HSMs and software HSM simulators (e.g. SoftHSM2) that
    implement the PKCS#11 standard -- the same code path works against either.

    Key material never leaves the HSM boundary: sign/encrypt/decrypt operations are
    performed via HSM sessions, never by extracting private key bytes (PKCS#11
    CKA_EXTRACTABLE=false is the default expectation for HSM-backed keys).

    The module/library path, slot, token label, and PIN are all operator-supplied
    configuration; the PIN in particular must be resolved through a secret reference
    (e.g. akaalEngine.connection.security.secret_consumer), never hardcoded.
    """

    PROVIDER_NAME = "PKCS11_HSM"

    def __init__(self, pkcs11_library_path: str, token_label: str, user_pin_provider, token: Optional[Any] = None) -> None:
        if not pkcs11_library_path or not token_label:
            raise ValueError("PKCS11HSMProvider requires pkcs11_library_path and token_label (operator-supplied).")
        self.pkcs11_library_path = pkcs11_library_path
        self.token_label = token_label
        self.user_pin_provider = user_pin_provider  # Callable[[], str] -- resolved on demand, never cached to disk
        self._lib = None
        # `token`: test-only SDK-interface double injection point (C4 hostile review),
        # matching the other providers' `client=` seam. Production callers never pass
        # this -- omitting it preserves the real pkcs11.lib()/get_token() construction.
        self._injected_token = token

    def _get_token(self):
        if self._injected_token is not None:
            return self._injected_token
        try:
            import pkcs11
        except ImportError as exc:
            raise KMSDependencyMissingError(
                "HSM operations require the 'python-pkcs11' library (pip install python-pkcs11) "
                "plus a PKCS#11 module (vendor HSM driver, or SoftHSM2 for local verification). "
                "The production PKCS#11 integration path is implemented; only the optional "
                "dependency/module is absent in this environment."
            ) from exc
        if self._lib is None:
            self._lib = pkcs11.lib(self.pkcs11_library_path)
        return self._lib.get_token(token_label=self.token_label)

    def _session(self):
        token = self._get_token()
        pin = self.user_pin_provider()
        if not pin:
            raise KMSProviderUnavailableError("HSM user PIN unavailable from configured provider (fail closed).")
        return token.open(user_pin=pin)

    def generate_key(self, purpose: KeyPurpose, algorithm: KeyAlgorithm) -> KeyReference:
        # _session() -> _get_token() performs the lazy `import pkcs11` and raises
        # KMSDependencyMissingError if python-pkcs11 is absent (unless a token is
        # injected for testing, in which case the real KeyType enum isn't needed either).
        label = f"akaal-{purpose.value.lower()}"
        with self._session() as session:
            if self._injected_token is not None:
                key_type_ec, key_type_aes = "EC_EDWARDS", "AES"
            else:
                from pkcs11 import KeyType
                key_type_ec, key_type_aes = KeyType.EC_EDWARDS, KeyType.AES
            if algorithm == KeyAlgorithm.ED25519:
                pub, priv = session.generate_keypair(key_type_ec, 256, label=label, store=True)
            else:
                priv = session.generate_key(key_type_aes, 256, label=label, store=True)
        return KeyReference(
            provider=self.PROVIDER_NAME, key_id=label, purpose=purpose,
            origin=KeyOrigin.HSM_BACKED, resource_id=f"{self.token_label}:{label}",
        )

    def _find_key(self, session, ref: KeyReference):
        if self._injected_token is not None:
            label_attr = "LABEL"
        else:
            import pkcs11
            label_attr = pkcs11.Attribute.LABEL
        objs = list(session.get_objects({label_attr: ref.key_id}))
        if not objs:
            raise KeyNotFoundError(f"HSM key with label {ref.key_id!r} not found on token {self.token_label!r}")
        return objs[0]

    def sign(self, ref: KeyReference, message: bytes) -> bytes:
        with self._session() as session:
            key = self._find_key(session, ref)
            return bytes(key.sign(message))

    def verify(self, ref: KeyReference, message: bytes, signature: bytes) -> bool:
        """
        C4/C5-class hostile-review fix (same defect category as Target 5's AWS fix):
        only a genuine cryptographic mismatch may return False. python-pkcs11 raises
        pkcs11.exceptions.SignatureInvalid specifically for a confirmed bad signature;
        any other exception (session/PIN/mechanism/device error) must propagate, not be
        silently reported as "verification failed". Matched by exception class name
        (works identically for the real pkcs11.exceptions.SignatureInvalid and for a
        test-only double raising a same-named exception, without requiring the real SDK
        to be importable in either code path).
        """
        with self._session() as session:
            key = self._find_key(session, ref)
            try:
                return bool(key.verify(message, signature))
            except Exception as exc:
                if type(exc).__name__ == "SignatureInvalid":
                    return False  # provider-confirmed genuine signature mismatch
                raise  # session/PIN/mechanism/device/unexpected error -- never silently False

    def encrypt(self, ref: KeyReference, plaintext: bytes, aad: Optional[bytes] = None) -> bytes:
        with self._session() as session:
            key = self._find_key(session, ref)
            return bytes(key.encrypt(plaintext))

    def decrypt(self, ref: KeyReference, ciphertext: bytes, aad: Optional[bytes] = None) -> bytes:
        with self._session() as session:
            key = self._find_key(session, ref)
            return bytes(key.decrypt(ciphertext))

    def rotate_key(self, purpose: KeyPurpose) -> KeyReference:
        raise KMSProviderUnavailableError(
            "HSM key rotation requires generating a new labeled key object and re-pointing "
            "callers at it (PKCS#11 has no in-place key rotation primitive); call "
            "generate_key() with a new label and manage the cutover explicitly."
        )

    def revoke_key(self, ref: KeyReference, reason: Optional[str] = None) -> None:
        with self._session() as session:
            key = self._find_key(session, ref)
            key.destroy()
