#!/usr/bin/env python3
import sys
import os

# Append the current integration test directory to system path targets
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import psycopg2
import pymysql
import oracledb

# --- BARE-METAL CONNECTION ENDPOINTS ---
DB_CONFIGS = {
    "oracle":   {"user": "akaal_admin", "pass": "AkaalPass2026", "dsn": "localhost:1521/FREEPDB1"},
    "mysql":    {"host": "localhost", "port": 3306, "user": "akaal_admin", "pass": "AkaalPass2026"},
    "pg_src":   {"host": "localhost", "port": 5432, "user": "akaal_admin", "pass": "AkaalPass2026", "db": "postgres"},
    "pg_tgt":   {"host": "localhost", "port": 5433, "user": "akaal_admin", "pass": "AkaalPass2026", "db": "postgres"}
}

def get_connection(engine):
    cfg = DB_CONFIGS[engine]
    if engine == "oracle":
        return oracledb.connect(user=cfg["user"], password=cfg["pass"], dsn=cfg["dsn"])
    elif engine == "mysql":
        return pymysql.connect(host=cfg["host"], port=cfg["port"], user=cfg["user"], password=cfg["pass"], autocommit=True)
    else:
        conn = psycopg2.connect(host=cfg["host"], port=cfg["port"], user=cfg["user"], password=cfg["pass"], database=cfg["db"])
        conn.autocommit = True
        return conn

def execute_statements(engine, statements):
    conn = get_connection(engine)
    cursor = conn.cursor()
    for stmt in statements:
        if not stmt.strip():
            continue
        try:
            cursor.execute(stmt)
        except Exception as e:
            print(f"[{engine.upper()} DDL Warning] Statement failed execution: {stmt[:60]}... -> Error: {e}")
    cursor.close()
    conn.close()

def deploy_schema_tier(size_label, table_count):
    print(f"\n[*] Generating structural components for tier: schema_{size_label} ({table_count} tables)...")
    
    for pg_engine in ["pg_src", "pg_tgt"]:
        pg_ddl = [
            f"DROP SCHEMA IF EXISTS schema_{size_label} CASCADE;",
            f"CREATE SCHEMA schema_{size_label};"
        ]
        for i in range(1, table_count + 1):
            pg_ddl.append(f"""
                CREATE TABLE schema_{size_label}.ent_asset_{i} (
                    id BIGSERIAL PRIMARY KEY,
                    uuid_val UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
                    title VARCHAR(255) DEFAULT 'Enterprise Standard Asset' NOT NULL,
                    meta_json JSONB,
                    payload_xml XML,
                    status_emoji VARCHAR(50) DEFAULT '????',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """)
            if i % 4 == 0:
                pg_ddl.append(f"CREATE INDEX idx_comp_{size_label}_{i} ON schema_{size_label}.ent_asset_{i} (uuid_val, created_at);")
                pg_ddl.append(f"ALTER TABLE schema_{size_label}.ent_asset_{i} ADD CONSTRAINT chk_title_{i} CHECK (char_length(title) > 3);")
            if i > 1 and i <= 100:
                pg_ddl.append(f"""
                    ALTER TABLE schema_{size_label}.ent_asset_{i} 
                    ADD COLUMN parent_ref_id BIGINT,
                    ADD CONSTRAINT fk_asset_rel_{i} FOREIGN KEY (parent_ref_id) 
                    REFERENCES schema_{size_label}.ent_asset_{i-1}(id) ON DELETE SET NULL;
                """)
        execute_statements(pg_engine, pg_ddl)

    mysql_db = f"mysql_schema_{size_label}"
    mysql_ddl = [
        f"DROP DATABASE IF EXISTS {mysql_db};",
        f"CREATE DATABASE {mysql_db};",
        f"USE {mysql_db};"
    ]
    for i in range(1, table_count + 1):
        mysql_ddl.append(f"""
            CREATE TABLE ent_asset_{i} (
                id BIGINT AUTO_INCREMENT PRIMARY KEY,
                uuid_val VARCHAR(36) NOT NULL UNIQUE,
                title VARCHAR(255) NOT NULL DEFAULT 'Enterprise Standard Asset',
                meta_json JSON,
                status_emoji VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT '????',
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            ) ENGINE=InnoDB;
        """)
        if i % 4 == 0:
            mysql_ddl.append(f"CREATE INDEX idx_comp_{size_label}_{i} ON ent_asset_{i} (uuid_val, created_at);")
        if i > 1 and i <= 100:
            mysql_ddl.append(f"""
                ALTER TABLE ent_asset_{i} 
                ADD COLUMN parent_ref_id BIGINT,
                ADD CONSTRAINT fk_asset_rel_{i} FOREIGN KEY (parent_ref_id) 
                REFERENCES ent_asset_{i-1}(id) ON DELETE SET NULL;
            """)
    execute_statements("mysql", mysql_ddl)

    oracle_ddl = []
    for i in range(1, table_count + 1):
        tbl_name = f"ORA_{size_label.upper()}_ASSET_{i}"
        try: execute_statements("oracle", [f"DROP TABLE {tbl_name} CASCADE CONSTRAINTS"])
        except: pass
        oracle_ddl.append(f"""
            CREATE TABLE {tbl_name} (
                id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                uuid_val VARCHAR2(36) NOT NULL UNIQUE,
                title VARCHAR2(255) DEFAULT 'Enterprise Standard Asset' NOT NULL,
                meta_json VARCHAR2(4000),
                payload_clob CLOB,
                payload_blob BLOB,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        if i % 4 == 0:
            oracle_ddl.append(f"CREATE INDEX idx_comp_{size_label}_{i} ON {tbl_name} (uuid_val, created_at)")
    execute_statements("oracle", oracle_ddl)

if __name__ == "__main__":
    print("==========================================================")
    deploy_schema_tier("small", 20)
    deploy_schema_tier("medium", 75)
    deploy_schema_tier("large", 200)
    print("\n==========================================================")
    print("? SCHEMA FACTORY COMPLETION: All structural layers deployed.")
    print("==========================================================")
