"""
AKAAL Enterprise Platform — Core Interfaces Architecture
=========================================================
Strict Protocol / Interface definitions for Control Plane and Data Plane layers.
"""

from typing import Any, Dict, List, Optional, Protocol, Tuple, Callable


class IRuntimeRegistry(Protocol):
    def register_runtime(self, runtime_id: str, migration_id: str, pid: int, metadata: Dict[str, Any]) -> None: ...
    def unregister_runtime(self, runtime_id: str) -> None: ...
    def get_runtime(self, runtime_id: str) -> Optional[Dict[str, Any]]: ...
    def get_runtime_by_migration(self, migration_id: str) -> Optional[Dict[str, Any]]: ...
    def update_heartbeat(self, runtime_id: str) -> None: ...
    def list_runtimes(self) -> List[Dict[str, Any]]: ...


class IStateStore(Protocol):
    def set_state(self, key: str, value: Any, category: str = "runtime") -> None: ...
    def get_state(self, key: str, default: Any = None) -> Any: ...
    def update_progress(self, migration_id: str, progress_data: Dict[str, Any]) -> None: ...
    def get_progress(self, migration_id: str) -> Dict[str, Any]: ...
    def snapshot(self) -> Dict[str, Any]: ...


class IEventBus(Protocol):
    def publish(self, topic: str, event_data: Dict[str, Any]) -> str: ...
    def subscribe(self, topic_pattern: str, handler: Callable[[str, Dict[str, Any]], None]) -> str: ...
    def unsubscribe(self, subscription_id: str) -> None: ...
    def replay_events(self, topic_pattern: str, from_sequence_id: int) -> List[Dict[str, Any]]: ...


class IMetadataCatalog(Protocol):
    def store_schema_metadata(self, schema_name: str, metadata: Dict[str, Any]) -> None: ...
    def get_schema_metadata(self, schema_name: str) -> Optional[Dict[str, Any]]: ...
    def get_table_metadata(self, schema_name: str, table_name: str) -> Optional[Dict[str, Any]]: ...
    def list_tables(self, schema_name: str) -> List[str]: ...


class IRecoveryCoordinator(Protocol):
    def initiate_recovery(self, migration_id: str, checkpoint_id: str) -> Dict[str, Any]: ...
    def verify_fencing_token(self, migration_id: str, token: str) -> bool: ...
    def replay_wal(self, migration_id: str, wal_segment_id: str) -> bool: ...


class IScheduler(Protocol):
    def schedule_partitions(self, migration_id: str, tables: List[str]) -> List[Dict[str, Any]]: ...
    def balance_queues(self, active_workers: int) -> None: ...
    def apply_backpressure(self, migration_id: str, paused: bool) -> None: ...


class IResourceManager(Protocol):
    def allocate_resources(self, migration_id: str, requested_workers: int) -> Dict[str, Any]: ...
    def release_resources(self, migration_id: str) -> None: ...
    def check_memory_pressure(self) -> bool: ...


class IPluginBus(Protocol):
    def register_plugin(self, hook_point: str, plugin_class: type) -> None: ...
    def execute_hooks(self, hook_point: str, context: Dict[str, Any]) -> Dict[str, Any]: ...


class IStorageProvider(Protocol):
    def write(self, key: str, value: bytes) -> bool: ...
    def read(self, key: str) -> Optional[bytes]: ...
    def delete(self, key: str) -> bool: ...
    def exists(self, key: str) -> bool: ...


class IIPCTransport(Protocol):
    def listen(self, endpoint: str) -> None: ...
    def send_response(self, client_id: str, response_payload: Dict[str, Any]) -> bool: ...
    def broadcast_event(self, event_payload: Dict[str, Any]) -> None: ...
    def close(self) -> None: ...
