"""
Akaal — Type Normalizer Implementation
======================================
Parses and standardizes raw vendor data type strings into structured DataType objects.
"""

import re
from typing import Optional, Tuple
from akaal.core.conversion.api.models import DataType, TypeCategory, DbVersion
from akaal.core.conversion.api.models import SpatialMetadata
from akaal.core.models.enums import SystemType
from akaal.core.conversion.exceptions import ValidationFailure

class TypeNormalizer:
    """Standardizes raw database data type strings into structured DataType models."""

    # Category matching regex patterns
    NUMERIC_PATTERNS = re.compile(
        r'\b(INT|INTEGER|BIGINT|SMALLINT|TINYINT|MEDIUMINT|DECIMAL|NUMERIC|NUMBER|FLOAT|DOUBLE|REAL|BINARY_FLOAT|BINARY_DOUBLE|DEC|NUM|MONEY)\b',
        re.IGNORECASE
    )
    STRING_PATTERNS = re.compile(
        r'\b(VARCHAR|VARCHAR2|NVARCHAR|CHAR|NCHAR|TEXT|NTEXT|CHARACTER VARYING|CHARACTER|VARYING|STRING)\b',
        re.IGNORECASE
    )
    DATETIME_PATTERNS = re.compile(
        r'\b(DATE|TIME|TIMESTAMP|DATETIME|DATETIME2|DATETIMEOFFSET|YEAR|TIMESTAMPTZ|TIMETZ|INTERVAL)\b',
        re.IGNORECASE
    )
    BOOLEAN_PATTERNS = re.compile(r'\b(BOOLEAN|BOOL|BIT)\b', re.IGNORECASE)
    BINARY_PATTERNS = re.compile(r'\b(BYTEA|BINARY|VARBINARY|RAW|IMAGE|ROWVERSION)\b', re.IGNORECASE)
    JSON_PATTERNS = re.compile(r'\b(JSON|JSONB)\b', re.IGNORECASE)
    UUID_PATTERNS = re.compile(r'\b(UUID|UNIQUEIDENTIFIER)\b', re.IGNORECASE)
    CLOB_PATTERNS = re.compile(r'\b(CLOB|NCLOB|TEXT|LONGTEXT|MEDIUMTEXT)\b', re.IGNORECASE)
    BLOB_PATTERNS = re.compile(r'\b(BLOB|LONGBLOB|MEDIUMBLOB|TINYBLOB)\b', re.IGNORECASE)
    LOB_PATTERNS = re.compile(r'\b(LOB)\b', re.IGNORECASE)

    def normalize(self, raw_type: str, vendor: str, version: DbVersion) -> DataType:
        """
        Parses a raw type string (e.g. 'varchar(255)', 'decimal(10,2) unsigned') into a DataType object.
        """
        if not raw_type or not raw_type.strip():
            raise ValidationFailure(errors=["Empty raw type string provided"])

        clean_raw = raw_type.strip().upper()
        
        # 1. Detect timezone awareness
        timezone = False
        if "WITH TIME ZONE" in clean_raw or "TIMESTAMPTZ" in clean_raw or "TZ" in clean_raw:
            timezone = True

        # 2. Detect unsigned flag
        unsigned = False
        if "UNSIGNED" in clean_raw:
            unsigned = True

        # 3. Detect identity/auto-increment
        auto_increment = False
        if any(kw in clean_raw for kw in ("IDENTITY", "AUTO_INCREMENT", "SERIAL", "BIGSERIAL", "GENERATED BY DEFAULT")):
            auto_increment = True

        # 4. Extract collation and charset metadata if present
        collation = None
        collation_match = re.search(r'\bCOLLATE\s+([A-Z0-9_]+)', clean_raw)
        if collation_match:
            collation = collation_match.group(1)

        charset = None
        charset_match = re.search(r'\bCHARACTER\s+SET\s+([A-Z0-9_-]+)', clean_raw)
        if charset_match:
            charset = charset_match.group(1)

        # 5. Extract core name and brackets parameters
        # Matches e.g. "VARCHAR2(255 BYTE)", "DECIMAL(10, 2)"
        name_match = re.match(r'^([A-Z0-9\s_]+)(?:\(([^)]+)\))?', clean_raw)
        if not name_match:
            raise ValidationFailure(errors=[f"Failed to parse structure of raw type: {raw_type}"])

        base_name_raw = name_match.group(1).strip()
        # Clean up descriptors like "UNSIGNED" or "WITH TIME ZONE" from base name
        base_name = re.sub(
            r'\b(UNSIGNED|WITH TIME ZONE|WITHOUT TIME ZONE|IDENTITY|AUTO_INCREMENT|CHARACTER SET \S+|COLLATE \S+)\b',
            '',
            base_name_raw
        ).strip()
        
        # Normalize double spaces
        base_name = " ".join(base_name.split())

        params_str = name_match.group(2)
        precision: Optional[int] = None
        scale: Optional[int] = None
        length: Optional[int] = None

        if params_str:
            params = [p.strip().split()[0] for p in params_str.split(",")]  # split '255 BYTE' to '255'
            if len(params) == 1:
                p_val = params[0]
                if p_val in ("MAX", "-1"):
                    length = -1
                elif p_val.isdigit():
                    val = int(p_val)
                    if self.STRING_PATTERNS.search(base_name) or self.BINARY_PATTERNS.search(base_name):
                        length = val
                    else:
                        precision = val
                else:
                    raise ValidationFailure(errors=[f"Invalid type parameter: {p_val}"])
            elif len(params) == 2:
                if params[0].isdigit() and params[1].isdigit():
                    precision = int(params[0])
                    scale = int(params[1])
                else:
                    raise ValidationFailure(errors=[f"Invalid type parameters: {params[0]}, {params[1]}"])
            else:
                raise ValidationFailure(errors=[f"Invalid number of parameters: {len(params)}"])

        # 6. Resolve type category
        category = self._resolve_category(base_name, raw_type)
        if base_name == "TINYINT" and precision == 1 and vendor.upper() in ("MYSQL", "MARIADB"):
            category = TypeCategory.BOOLEAN

        # 7. Apply standard vendor defaults if not specified
        # This aligns with the 'default precision/scale' requirement.
        precision, scale, length = self._apply_vendor_defaults(
            base_name, category, precision, scale, length, vendor
        )

        return DataType(
            name=base_name,
            category=category,
            precision=precision,
            scale=scale,
            length=length,
            nullable=True,  # Default nullable, overridden at pipeline or validation level
            unsigned=unsigned,
            auto_increment=auto_increment,
            timezone=timezone,
            charset=charset,
            collation=collation,
            spatial=None,  # Handled by dynamic providers/plugins
            is_array=False,
            array_dimensions=None,
            generated_expression=None,
            vendor_metadata={}
        )

    def _resolve_category(self, base_name: str, raw_type: str) -> TypeCategory:
        # Check specific strings first
        if self.JSON_PATTERNS.search(base_name):
            return TypeCategory.JSON
        if self.UUID_PATTERNS.search(base_name):
            return TypeCategory.UUID
        if self.CLOB_PATTERNS.search(base_name):
            return TypeCategory.CLOB
        if self.BLOB_PATTERNS.search(base_name):
            return TypeCategory.BLOB
        if self.LOB_PATTERNS.search(base_name):
            return TypeCategory.LOB
        if self.BOOLEAN_PATTERNS.search(base_name):
            return TypeCategory.BOOLEAN
        if self.NUMERIC_PATTERNS.search(base_name):
            return TypeCategory.NUMERIC
        if self.STRING_PATTERNS.search(base_name):
            return TypeCategory.STRING
        if self.DATETIME_PATTERNS.search(base_name):
            return TypeCategory.DATE_TIME
        if self.BINARY_PATTERNS.search(base_name):
            return TypeCategory.BINARY
        
        # Safe fallback
        return TypeCategory.STRING

    def _apply_vendor_defaults(
        self,
        base_name: str,
        category: TypeCategory,
        precision: Optional[int],
        scale: Optional[int],
        length: Optional[int],
        vendor: str
    ) -> Tuple[Optional[int], Optional[int], Optional[int]]:
        """Applies database system defaults for precision, scale, and length when not specified."""
        v_upper = vendor.upper()
        
        if category == TypeCategory.NUMERIC:
            if "DECIMAL" in base_name or "NUMERIC" in base_name or "NUMBER" in base_name:
                if precision is None:
                    if "POSTGRESQL" in v_upper:
                        # Postgres numeric has no default limit in catalog, but typically defaults to 38,0 or None
                        pass
                    elif "MYSQL" in v_upper:
                        precision, scale = 10, 0
                    elif "ORACLE" in v_upper:
                        precision, scale = 38, 0
                    elif "MSSQL" in v_upper or "SQL Server" in v_upper:
                        precision, scale = 18, 0
                elif scale is None:
                    scale = 0

        elif category == TypeCategory.STRING:
            # If length is not defined, we leave it None or default depending on policy.
            # However, some vendors have specific default lengths, e.g. VARCHAR in SQL Server defaults to 1.
            pass

        return precision, scale, length
