"""
Akaal — Compression-Aware Domain Models
=======================================
Immutable dataclasses and enums modeling database compression strategies,
capabilities, metrics, translations, and diagnostics.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, Optional, Tuple

from akaal.core.models.enums import SystemType
from akaal.core.intelligence.common.models import ReportMetadata, Diagnostic


class CompressionAlgorithm(str, Enum):
    """Supported vendor-independent and vendor-specific compression algorithms."""
    NONE = "NONE"
    LZ4 = "LZ4"
    LZMA = "LZMA"
    ZSTD = "ZSTD"
    ZLIB = "ZLIB"
    GZIP = "GZIP"
    PGLZ = "PGLZ"
    SNAPPY = "SNAPPY"
    BROTLI = "BROTLI"
    ROW = "ROW"
    PAGE = "PAGE"
    COLUMNSTORE = "COLUMNSTORE"
    TOAST = "TOAST"
    ADVANCED_ROW = "ADVANCED_ROW"
    HCC_QUERY_LOW = "HCC_QUERY_LOW"
    HCC_QUERY_HIGH = "HCC_QUERY_HIGH"
    HCC_ARCHIVE_LOW = "HCC_ARCHIVE_LOW"
    HCC_ARCHIVE_HIGH = "HCC_ARCHIVE_HIGH"


class CompressionCompatibilityTier(str, Enum):
    """Compatibility ranking metrics mapping source-to-target compression translations."""
    NATIVE = "NATIVE"
    LOSSLESS_TRANSLATION = "LOSSLESS_TRANSLATION"
    LOSSY_TRANSLATION = "LOSSY_TRANSLATION"
    EMULATED = "EMULATED"
    PLUGIN_PROVIDED = "PLUGIN_PROVIDED"
    UNSUPPORTED = "UNSUPPORTED"


@dataclass(frozen=True)
class CompressionProfile:
    """Configured compression profile for a specific storage engine layout."""
    profile_id: str
    dialect: SystemType
    engine_name: str
    algorithm: CompressionAlgorithm
    block_size_kb: int
    compression_level: int = 1
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CompressionCapability:
    """Capability descriptor of a database dialect supporting a compression format."""
    dialect: SystemType
    supported_algorithms: Tuple[CompressionAlgorithm, ...]
    min_version: str
    requires_enterprise: bool = False
    requires_plugin: bool = False


@dataclass(frozen=True)
class CompressionRule:
    """Matching rule mapped in the Strategy Registry."""
    rule_id: str
    rule_name: str
    target_dialect: SystemType
    priority: int
    min_row_count: int
    target_column_types: Tuple[str, ...]
    recommended_profile: CompressionProfile
    min_version: Optional[str] = None
    max_version: Optional[str] = None
    required_engine: Optional[str] = None
    required_edition: Optional[str] = None


@dataclass(frozen=True)
class CompressionScore:
    """Scored evaluation of a target compression profile suggestion."""
    confidence: float
    priority: int
    expected_storage_benefit: float
    expected_cpu_impact: float
    expected_io_benefit: float
    implementation_complexity: int
    migration_risk: int
    maintenance_impact: int
    rationale: str
    evidence: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CompressionRecommendation:
    """Immutable advisory suggestion recommending table or index compression."""
    recommendation_id: str
    title: str
    description: str
    target_object_path: str
    score: CompressionScore


@dataclass(frozen=True)
class CompressionTranslation:
    """Detailed compression mapping plan converting compression from source to target dialect."""
    source_dialect: SystemType
    target_dialect: SystemType
    source_algorithm: CompressionAlgorithm
    target_algorithm: CompressionAlgorithm
    compatibility_tier: CompressionCompatibilityTier
    translation_confidence: float
    translation_rationale: str
    translation_path: Tuple[str, ...]
    estimated_ratio_loss: float
    supporting_evidence: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class CompressionStatistics:
    """Reduction counts, estimated space savings, and CPU cycles overhead metrics."""
    total_uncompressed_size_kb: int
    total_projected_size_kb: int
    estimated_savings_kb: int
    average_compression_ratio: float
    cpu_overhead_factor: float
    io_throughput_multiplier: float


@dataclass(frozen=True)
class CompressionSummary:
    """High-level compression mapping indicators."""
    total_tables_analyzed: int
    compressed_tables_count: int
    native_mappings_count: int
    translated_mappings_count: int
    unsupported_mappings_count: int


@dataclass(frozen=True)
class CompressionReport:
    """Unified immutable outcome model generated by the compression subsystem."""
    metadata: ReportMetadata
    statistics: CompressionStatistics
    summary: CompressionSummary
    translations: Dict[str, CompressionTranslation]
    recommendations: Tuple[CompressionRecommendation, ...]
    diagnostics: Tuple[Diagnostic, ...]
    warnings: Tuple[str, ...]
