"""
AKAAL CDC Replication Loop & Echo Prevention Filter.
=====================================================
Prevents infinite replication loops (A -> B -> A) by inspecting canonical origin provenance tags.
Suppresses echo events captured from peer writes while preserving legitimate local mutations.
"""

import logging
import threading
from typing import Dict, Any, Optional, Set

from akaal.cdc.domain.events import CDCTransaction, CDCEventIdentity
from akaal.cdc.domain.errors import CDCExecutionError, CDCFailure, CDCFailureType, CDCFailureCategory
from akaal.cdc.multi_master.domain import CDCOriginProvenance

logger = logging.getLogger("akaal.cdc.multi_master.loop_filter")


class CDCReplicationLoopFilter:
    """
    Backend-authoritative CDC replication loop filter.
    Enforces deterministic echo suppression based on identity-bound origin provenance.
    """

    def __init__(
        self,
        local_database_id: str,
        topology_id: str,
        run_id: str,
        akaal_writer_id: Optional[str] = None,
        max_hops: int = 5,
    ) -> None:
        self.local_database_id = local_database_id
        self.topology_id = topology_id
        self.run_id = run_id
        self.akaal_writer_id = akaal_writer_id or f"writer-{local_database_id}"
        self.max_hops = max_hops

        self._lock = threading.RLock()
        self.echo_events_suppressed_count: int = 0
        self.processed_events_count: int = 0

    def attach_origin_provenance(
        self,
        transaction: CDCTransaction,
        direction: str,
    ) -> CDCTransaction:
        """
        Attaches canonical CDCOriginProvenance tag to transaction metadata before target apply.
        """
        with self._lock:
            prov = CDCOriginProvenance(
                origin_database_id=self.local_database_id,
                origin_topology_id=self.topology_id,
                origin_run_id=self.run_id,
                akaal_writer_id=self.akaal_writer_id,
                replication_direction=direction,
                hop_count=1,
                origin_tx_id=transaction.tx_id,
            )
            # Store in event details / transaction metadata
            for event in transaction.events:
                if not hasattr(event, 'details') or event.details is None:
                    event.details = {}
                event.details["origin_provenance"] = prov.to_dict()
            return transaction

    def should_suppress_transaction(
        self,
        transaction: CDCTransaction,
        identity: CDCEventIdentity,
    ) -> bool:
        """
        Evaluates whether transaction is an echo change generated by AKAAL on peer database.
        Returns True if transaction MUST BE SUPPRESSED from local apply.
        Raises CDCExecutionError(INVALID_ORIGIN_PROVENANCE) on malformed or cross-topology provenance.
        """
        with self._lock:
            self.processed_events_count += 1

            for event in transaction.events:
                details = getattr(event, 'details', {}) or {}
                prov_dict = details.get("origin_provenance")
                if not prov_dict:
                    # Legitimate native local write without AKAAL provenance tag
                    continue

                if not isinstance(prov_dict, dict):
                    fail = CDCFailure(
                        failure_type=CDCFailureType.INVALID_ORIGIN_PROVENANCE,
                        category=CDCFailureCategory.BLOCKING,
                        message=f"[INVALID PROVENANCE] Transaction '{transaction.tx_id}' contains malformed provenance dictionary.",
                        migration_id=identity.migration_id,
                        job_id=identity.job_id,
                        run_id=identity.run_id,
                        cdc_session_id=identity.cdc_session_id,
                    )
                    raise CDCExecutionError(fail)

                try:
                    prov = CDCOriginProvenance.from_dict(prov_dict)
                except Exception as exc:
                    fail = CDCFailure(
                        failure_type=CDCFailureType.INVALID_ORIGIN_PROVENANCE,
                        category=CDCFailureCategory.BLOCKING,
                        message=f"[INVALID PROVENANCE] Failed to parse origin provenance for transaction '{transaction.tx_id}': {exc}",
                        migration_id=identity.migration_id,
                        job_id=identity.job_id,
                        run_id=identity.run_id,
                        cdc_session_id=identity.cdc_session_id,
                    )
                    raise CDCExecutionError(fail)

                # Cross-topology or cross-run substitution rejection
                if prov.origin_topology_id != self.topology_id:
                    fail = CDCFailure(
                        failure_type=CDCFailureType.TOPOLOGY_IDENTITY_MISMATCH,
                        category=CDCFailureCategory.BLOCKING,
                        message=f"[TOPOLOGY MISMATCH] Origin topology '{prov.origin_topology_id}' does not match local topology '{self.topology_id}'.",
                        migration_id=identity.migration_id,
                        job_id=identity.job_id,
                        run_id=identity.run_id,
                        cdc_session_id=identity.cdc_session_id,
                    )
                    raise CDCExecutionError(fail)

                if prov.origin_run_id != self.run_id:
                    fail = CDCFailure(
                        failure_type=CDCFailureType.TOPOLOGY_IDENTITY_MISMATCH,
                        category=CDCFailureCategory.BLOCKING,
                        message=f"[RUN MISMATCH] Origin run '{prov.origin_run_id}' does not match local run '{self.run_id}'.",
                        migration_id=identity.migration_id,
                        job_id=identity.job_id,
                        run_id=identity.run_id,
                        cdc_session_id=identity.cdc_session_id,
                    )
                    raise CDCExecutionError(fail)

                # Hop count overflow protection
                if prov.hop_count > self.max_hops:
                    fail = CDCFailure(
                        failure_type=CDCFailureType.REPLICATION_LOOP_DETECTED,
                        category=CDCFailureCategory.BLOCKING,
                        message=f"[LOOP DETECTED] Bounded hop count exceeded ({prov.hop_count} > {self.max_hops}) for tx '{transaction.tx_id}'.",
                        migration_id=identity.migration_id,
                        job_id=identity.job_id,
                        run_id=identity.run_id,
                        cdc_session_id=identity.cdc_session_id,
                    )
                    raise CDCExecutionError(fail)

                # ECHO SUPPRESSION DETECTED:
                # If change originated from this database, OR applied by this writer instance
                if prov.origin_database_id == self.local_database_id or prov.akaal_writer_id == self.akaal_writer_id:
                    self.echo_events_suppressed_count += 1
                    logger.info(
                        f"[LoopFilter] Suppressed echo transaction '{transaction.tx_id}' "
                        f"(Origin DB: '{prov.origin_database_id}', Writer: '{prov.akaal_writer_id}')."
                    )
                    return True

            return False

    def get_telemetry(self) -> Dict[str, Any]:
        """Returns filter telemetry counters."""
        with self._lock:
            return {
                "local_database_id": self.local_database_id,
                "topology_id": self.topology_id,
                "run_id": self.run_id,
                "echo_events_suppressed_count": self.echo_events_suppressed_count,
                "processed_events_count": self.processed_events_count,
                "filter_health": "HEALTHY",
            }
