"""SimulationEngine & SimulationReport for dry-run simulation."""

import time
from typing import Dict, Any, List
from dataclasses import dataclass, field
from akaal.healing.sandbox.predictor import RiskPredictor


@dataclass
class SimulationReport:
    """Detailed report generated by dry-run repair simulation."""

    plan_id: str
    predicted_duration_ms: float
    rollback_probability: float
    expected_success_rate: float
    affected_tables: List[str]
    is_safe: bool
    timestamp: float = field(default_factory=time.time)


class SimulationEngine:
    """Simulates repair plan execution without modifying production data."""

    def __init__(self):
        self.predictor = RiskPredictor()

    def simulate(self, plan: Any) -> SimulationReport:
        """Run dry-run simulation over plan."""
        pred = self.predictor.predict(plan)
        tables = []
        for step in getattr(plan, "steps", []):
            for action in getattr(step, "actions", []):
                if action.target_table and action.target_table not in tables:
                    tables.append(action.target_table)

        return SimulationReport(
            plan_id=getattr(plan, "plan_id", "plan_sim"),
            predicted_duration_ms=pred["estimated_duration_ms"],
            rollback_probability=pred["rollback_probability"],
            expected_success_rate=pred["predicted_success_rate"],
            affected_tables=tables,
            is_safe=pred["rollback_probability"] < 0.10,
        )
