"""
tests.unit.engine_schema.test_target_ddl_dialects
=================================================
Unit tests proving syntax-exact target DDL generation across relational and warehouse dialects (SCH-027 to SCH-034).
"""

import pytest

from akaalEngine.schema.ddl.emitter import DDLStage
from akaalEngine.schema.ddl.generator import DDLGenerator
from akaalEngine.schema.models.constraints import CanonicalForeignKey, CanonicalPrimaryKey
from akaalEngine.schema.models.indexes import CanonicalIndex
from akaalEngine.schema.models.partitioning import CanonicalPartitioning, PartitionStrategy
from akaalEngine.schema.models.schema import CanonicalSchema, CanonicalSchemaModel, CanonicalView
from akaalEngine.schema.models.table import CanonicalColumn, CanonicalTable
from akaalEngine.schema.models.types import CanonicalType, CanonicalTypeCategory


def _create_sample_model():
    col_id = CanonicalColumn(
        name="id",
        ordinal_position=1,
        source_native_type="BIGINT",
        canonical_type=CanonicalType(category=CanonicalTypeCategory.EXACT_NUMERIC, raw_vendor_type="BIGINT", bits=64),
        nullable=False,
        is_identity=True,
    )
    col_cust = CanonicalColumn(
        name="customer_id",
        ordinal_position=2,
        source_native_type="INT",
        canonical_type=CanonicalType(category=CanonicalTypeCategory.EXACT_NUMERIC, raw_vendor_type="INT", bits=32),
        nullable=False,
    )
    col_data = CanonicalColumn(
        name="payload",
        ordinal_position=3,
        source_native_type="JSONB",
        canonical_type=CanonicalType(category=CanonicalTypeCategory.JSON, raw_vendor_type="JSONB"),
    )

    pk = CanonicalPrimaryKey(name="pk_orders", table_name="orders", columns=("id",), schema_name="sales")
    fk = CanonicalForeignKey(
        name="fk_orders_cust",
        table_name="orders",
        schema_name="sales",
        columns=("customer_id",),
        referenced_schema="sales",
        referenced_table="customers",
        referenced_columns=("id",),
    )
    idx = CanonicalIndex(name="idx_orders_cust", table_name="orders", schema_name="sales", columns=("customer_id",))

    tbl = CanonicalTable(
        table_name="orders",
        schema_name="sales",
        columns=(col_id, col_cust, col_data),
        primary_key=pk,
        foreign_keys=(fk,),
        indexes=(idx,),
        partitioning=CanonicalPartitioning(
            strategy=PartitionStrategy.RANGE,
            partition_columns=("order_date",),
        ),
    )

    view = CanonicalView(view_name="v_orders", schema_name="sales", definition_sql="SELECT id, customer_id FROM sales.orders")

    return CanonicalSchemaModel(
        model_id="test_ddl_estate",
        source_vendor="POSTGRESQL",
        schemas=(CanonicalSchema(schema_name="sales"),),
        tables=(tbl,),
        views=(view,),
    )


def test_postgresql_ddl_generation():
    model = _create_sample_model()
    pkg = DDLGenerator.generate_ddl_package(model, "POSTGRESQL")
    assert pkg.target_engine == "POSTGRESQL"

    schemas = pkg.get_stage_artifacts(DDLStage.SCHEMAS)
    assert len(schemas) >= 1
    assert 'CREATE SCHEMA IF NOT EXISTS "sales";' in schemas[0].sql

    tables = pkg.get_stage_artifacts(DDLStage.TABLES)
    assert len(tables) == 1
    assert 'CREATE TABLE IF NOT EXISTS "sales"."orders"' in tables[0].sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in tables[0].sql

    indexes = pkg.get_stage_artifacts(DDLStage.INDEXES)
    assert len(indexes) == 1
    assert 'CREATE INDEX IF NOT EXISTS "idx_orders_cust" ON "sales"."orders"' in indexes[0].sql

    fks = pkg.get_stage_artifacts(DDLStage.FOREIGN_KEYS)
    assert len(fks) == 1
    assert 'ALTER TABLE "sales"."orders" ADD CONSTRAINT "fk_orders_cust"' in fks[0].sql


def test_snowflake_ddl_generation():
    model = _create_sample_model()
    pkg = DDLGenerator.generate_ddl_package(model, "SNOWFLAKE")
    assert pkg.target_engine == "SNOWFLAKE"

    tables = pkg.get_stage_artifacts(DDLStage.TABLES)
    assert len(tables) == 1
    assert 'CREATE TABLE IF NOT EXISTS "SALES"."ORDERS"' in tables[0].sql
    assert "CLUSTER BY" in tables[0].sql


def test_bigquery_ddl_generation():
    model = _create_sample_model()
    pkg = DDLGenerator.generate_ddl_package(model, "BIGQUERY")
    assert pkg.target_engine == "BIGQUERY"

    tables = pkg.get_stage_artifacts(DDLStage.TABLES)
    assert len(tables) == 1
    assert "CREATE TABLE IF NOT EXISTS `sales`.`orders`" in tables[0].sql
    assert "PARTITION BY DATE(`order_date`)" in tables[0].sql


def test_cql_ddl_generation():
    model = _create_sample_model()
    pkg = DDLGenerator.generate_ddl_package(model, "CASSANDRA")
    assert pkg.target_engine == "CASSANDRA"

    schemas = pkg.get_stage_artifacts(DDLStage.SCHEMAS)
    assert len(schemas) == 1
    assert 'CREATE KEYSPACE IF NOT EXISTS "sales"' in schemas[0].sql
