import unittest
from typing import List, Tuple
from akaal.core.models.enums import SystemType
from akaal.migration.models import (
    ObjectType, OperationType, Table, Column, Partition, PartitionType,
    IdentityMetadata, PartitionBoundary, PartitionMetadata, MigrationOperation
)
from akaal.migration.ddl import DDLGeneratorRegistry
from akaal.migration.reliability.context.reliability_context import ReliabilityContext
from akaal.migration.reliability.models.diagnostics import ReliabilityDiagnostic
from akaal.migration.reliability.validation.object_validator import (
    IdentityCapabilityValidator, PartitionCapabilityValidator
)
from akaal.migration.versioning import (
    ObjectVersionHistory, ObjectVersionComparer, VersionRegistry, ConcurrencyConflictError
)
from akaal.migration.execution.scheduler import (
    ParallelScheduler, ScheduledPlan, ExecutionWave, ScheduledOperation
)

class TestDay4SyncFeatures(unittest.TestCase):
    def test_postgres_identity_column_ddl(self) -> None:
        col = Column(
            name="id",
            data_type="INTEGER",
            nullable=False,
            identity=IdentityMetadata(always=True, start=10, increment=2, min_value=5, max_value=1000, cycle=True)
        )
        pg_gen = DDLGeneratorRegistry.get_generator(SystemType.POSTGRESQL)
        op = MigrationOperation(operation_id="op_1", operation_type=OperationType.CREATE, target_object=col)
        cmds = pg_gen.generate_commands([op])
        self.assertEqual(len(cmds), 1)
        sql = cmds[0].sql
        self.assertIn("GENERATED ALWAYS AS IDENTITY", sql)
        self.assertIn("START WITH 10", sql)
        self.assertIn("INCREMENT BY 2", sql)
        self.assertIn("MINVALUE 5", sql)
        self.assertIn("MAXVALUE 1000", sql)
        self.assertIn("CYCLE", sql)

    def test_oracle_identity_column_ddl(self) -> None:
        col = Column(
            name="id",
            data_type="NUMBER",
            nullable=False,
            identity=IdentityMetadata(always=False, start=1, increment=1)
        )
        ora_gen = DDLGeneratorRegistry.get_generator(SystemType.ORACLE)
        op = MigrationOperation(operation_id="op_1", operation_type=OperationType.CREATE, target_object=col)
        cmds = ora_gen.generate_commands([op])
        sql = cmds[0].sql
        self.assertIn("GENERATED BY DEFAULT ON NULL AS IDENTITY", sql)

    def test_sqlserver_identity_column_ddl(self) -> None:
        col = Column(
            name="id",
            data_type="INT",
            nullable=False,
            identity=IdentityMetadata(start=100, increment=10)
        )
        mssql_gen = DDLGeneratorRegistry.get_generator(SystemType.MSSQL)
        op = MigrationOperation(operation_id="op_1", operation_type=OperationType.CREATE, target_object=col)
        cmds = mssql_gen.generate_commands([op])
        sql = cmds[0].sql
        self.assertIn("IDENTITY(100,10)", sql)

    def test_table_partitioning_postgresql_ddl(self) -> None:
        part = Partition(
            name="part_2026",
            table_name="sales",
            partition_type=PartitionType.RANGE,
            expression="sale_date",
            values=("'2026-01-01'", "'2027-01-01'")
        )
        pg_gen = DDLGeneratorRegistry.get_generator(SystemType.POSTGRESQL)
        op = MigrationOperation(operation_id="op_1", operation_type=OperationType.CREATE, target_object=part)
        cmds = pg_gen.generate_commands([op])
        self.assertEqual(len(cmds), 1)
        sql = cmds[0].sql
        self.assertIn("CREATE TABLE", sql)
        self.assertIn('PARTITION OF "sales" FOR VALUES FROM', sql)
        self.assertIn("'2026-01-01'", sql)

    def test_object_versioning(self) -> None:
        history = ObjectVersionHistory()
        col1 = Column(name="user_id", data_type="INT")
        
        # Initial commit
        snap1 = history.commit_version(col1, created_by="developer_1", tags=("v1.0",))
        self.assertEqual(snap1.metadata.change_type, "CREATE")
        self.assertEqual(snap1.metadata.tags, ("v1.0",))
        
        # Second commit (no actual change)
        snap2 = history.commit_version(col1, created_by="developer_1", expected_parent_id=snap1.metadata.version_id)
        self.assertEqual(snap2.metadata.change_type, "NONE")
        self.assertEqual(snap2.metadata.parent_version_id, snap1.metadata.version_id)

        # Modifying properties and committing
        col1_modified = Column(name="user_id", data_type="BIGINT")
        snap3 = history.commit_version(col1_modified, created_by="developer_2", expected_parent_id=snap2.metadata.version_id)
        self.assertEqual(snap3.metadata.change_type, "UPDATE")

        # Concurrency Conflict
        with self.assertRaises(ConcurrencyConflictError):
            history.commit_version(col1_modified, created_by="developer_3", expected_parent_id=snap1.metadata.version_id)

    def test_version_comparer(self) -> None:
        history = ObjectVersionHistory()
        col1 = Column(name="email", data_type="VARCHAR(255)")
        snap1 = history.commit_version(col1, created_by="admin")

        col2 = Column(name="email", data_type="VARCHAR(500)")
        snap2 = history.commit_version(col2, created_by="admin", expected_parent_id=snap1.metadata.version_id)

        comparer = ObjectVersionComparer()
        diff = comparer.compare(snap1, snap2)
        self.assertEqual(diff.change_type, "UPDATE")
        self.assertTrue(diff.diff_details.get("schema_changed"))

    def test_parallel_scheduler(self) -> None:
        scheduler = ParallelScheduler(worker_count=2)
        
        op1 = MigrationOperation(operation_id="op_1", operation_type=OperationType.CREATE, target_object=Table(name="t1"))
        op2 = MigrationOperation(operation_id="op_2", operation_type=OperationType.CREATE, target_object=Table(name="t2"))
        # op3 depends on op1
        op3 = MigrationOperation(
            operation_id="op_3",
            operation_type=OperationType.CREATE,
            target_object=Table(name="t3"),
            depends_on=("op_1",)
        )
        
        schedule = scheduler.generate_schedule([op1, op2, op3])
        self.assertEqual(schedule.statistics["stages_count"], 1)
        self.assertGreaterEqual(schedule.statistics["total_waves"], 2)

    def test_capability_validators(self) -> None:
        # Mock Context with MSSQL target
        from akaal.migration.reliability.context import ReliabilityContext, ValidationConfiguration, RuntimeMetadata
        from akaal.migration.models import ExecutionContext
        from akaal.migration.ddl.utilities.capabilities import DialectCapabilities
        
        exec_ctx = ExecutionContext().with_metadata("target_dialect", SystemType.MSSQL)
        
        context = ReliabilityContext(
            migration_plan=None,
            schema_report=None,
            validation_config=ValidationConfiguration(),
            capabilities=DialectCapabilities(),
            execution_context=exec_ctx,
            runtime_metadata=RuntimeMetadata(
                pipeline_run_id="test_run",
                started_at=123.45,
                caller_identity="QA",
                target_environment="dev"
            )
        )

        val_id = IdentityCapabilityValidator()
        col = Column(name="id", identity=IdentityMetadata(cycle=True))
        diag_id = val_id.validate_object(col, context)
        self.assertEqual(len(diag_id), 1)
        self.assertIn("does not support sequence CYCLE behavior", diag_id[0].message)

        val_part = PartitionCapabilityValidator()
        table = Table(
            name="users",
            partition_metadata=PartitionMetadata(
                partition_type=PartitionType.HASH,
                partition_keys=("id",),
                boundaries={}
            )
        )
        diag_part = val_part.validate_object(table, context)
        self.assertEqual(len(diag_part), 1)
        self.assertIn("only natively supports RANGE partitioning", diag_part[0].message)
