"""
Akaal — Encryption Domain Models
================================
Defines frozen dataclasses and enums for the Encryption-Aware subsystem.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, Optional, Tuple

from akaal.core.models.enums import SystemType
from akaal.core.intelligence.common.models import ReportMetadata, Diagnostic

class EncryptionAlgorithm(str, Enum):
    AES128 = "AES128"
    AES192 = "AES192"
    AES256 = "AES256"
    TRIPLE_DES = "3DES"
    BLOWFISH = "BLOWFISH"
    CHACHA20 = "CHACHA20"
    NATIVE_TDE = "NATIVE_TDE"

class EncryptionMode(str, Enum):
    CBC = "CBC"
    CTR = "CTR"
    GCM = "GCM"
    ECB = "ECB"
    XTS = "XTS"

class KeyManagementProvider(str, Enum):
    LOCAL_WALLET = "LOCAL_WALLET"
    AWS_KMS = "AWS_KMS"
    AZURE_KEY_VAULT = "AZURE_KEY_VAULT"
    HASHICORP_VAULT = "HASHICORP_VAULT"
    ORACLE_OKV = "ORACLE_OKV"
    GCP_KMS = "GCP_KMS"

class KeyRotationPolicy(str, Enum):
    AUTOMATIC_90_DAYS = "AUTOMATIC_90_DAYS"
    AUTOMATIC_180_DAYS = "AUTOMATIC_180_DAYS"
    AUTOMATIC_365_DAYS = "AUTOMATIC_365_DAYS"
    MANUAL = "MANUAL"
    NONE = "NONE"

class EncryptionCompatibilityTier(str, Enum):
    NATIVE = "NATIVE"
    REQUIRES_KEY_ROTATION = "REQUIRES_KEY_ROTATION"
    REQUIRES_MANUAL_MIGRATION = "REQUIRES_MANUAL_MIGRATION"
    PLUGIN_PROVIDED = "PLUGIN_PROVIDED"
    UNSUPPORTED = "UNSUPPORTED"

@dataclass(frozen=True)
class EncryptionProfile:
    """Configured encryption configuration profile for storage or transport layout."""
    profile_id: str
    dialect: SystemType
    engine_name: str
    algorithm: EncryptionAlgorithm
    mode: EncryptionMode
    key_provider: KeyManagementProvider
    rotation_policy: KeyRotationPolicy
    key_length_bits: int

@dataclass(frozen=True)
class EncryptionCapability:
    """TDE and key exchange capabilities supported by a target version/edition context."""
    dialect: SystemType
    supported_algorithms: Tuple[EncryptionAlgorithm, ...]
    supported_modes: Tuple[EncryptionMode, ...]
    supported_providers: Tuple[KeyManagementProvider, ...]
    min_version: str
    requires_enterprise: bool

@dataclass(frozen=True)
class EncryptionRule:
    """Matching rule registered for target engine placement negotiations."""
    rule_id: str
    rule_name: str
    target_dialect: SystemType
    priority: int
    min_version: Optional[str] = None
    max_version: Optional[str] = None
    required_engine: Optional[str] = None
    required_edition: Optional[str] = None
    recommended_profile: Optional[EncryptionProfile] = None

@dataclass(frozen=True)
class EncryptionScore:
    """Weighted metrics evaluation mapping optimization outcomes."""
    confidence: float
    priority: int
    security_improvement: float
    migration_complexity: int
    operational_risk: int
    compliance_impact: float
    performance_impact: float
    implementation_effort: int
    rationale: str
    evidence: Dict[str, Any] = field(default_factory=dict)

@dataclass(frozen=True)
class EncryptionRecommendation:
    """Immutable advisory suggestion for securing database files or columns."""
    recommendation_id: str
    title: str
    description: str
    target_object_path: str
    score: EncryptionScore

@dataclass(frozen=True)
class EncryptionTranslation:
    """Capability conversion mapping from source to target encryption configuration."""
    source_dialect: SystemType
    target_dialect: SystemType
    source_algorithm: EncryptionAlgorithm
    target_algorithm: EncryptionAlgorithm
    compatibility_tier: EncryptionCompatibilityTier
    translation_confidence: float
    translation_rationale: str
    translation_path: Tuple[str, ...]
    estimated_performance_overhead: float

@dataclass(frozen=True)
class EncryptionStatistics:
    """High-level metrics mapping translation coverage."""
    total_objects_analyzed: int
    encrypted_objects_count: int
    native_mappings_count: int
    translated_mappings_count: int
    unsupported_mappings_count: int
    average_confidence: float

@dataclass(frozen=True)
class EncryptionSummary:
    """Subsystem compliance outcome indicators."""
    has_compliant_algorithms: bool
    requires_manual_intervention: bool
    requires_key_rotation_setup: bool
    missing_kms_providers: Tuple[str, ...]

@dataclass(frozen=True)
class EncryptionReport:
    """Outcome model generated by the encryption subsystem."""
    metadata: ReportMetadata
    statistics: EncryptionStatistics
    summary: EncryptionSummary
    translations: Dict[str, EncryptionTranslation]
    recommendations: Tuple[EncryptionRecommendation, ...]
    diagnostics: Tuple[Diagnostic, ...]
    warnings: Tuple[str, ...]
